
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 03 21:39:22 MST 2025
//----------------------------------------------------

package codigo;

import java_cup.runtime.Symbol;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Wed Dec 03 21:39:22 MST 2025
  */
public class Sintaxis extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintaxis() {super();}

  /** Constructor which sets the default scanner. */
  public Sintaxis(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintaxis(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\152\000\002\002\004\000\002\002\012\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\005\007\000" +
    "\002\006\004\000\002\006\003\000\002\007\003\000\002" +
    "\007\003\000\002\007\003\000\002\010\006\000\002\011" +
    "\004\000\002\011\003\000\002\012\011\000\002\025\003" +
    "\000\002\025\005\000\002\013\006\000\002\014\004\000" +
    "\002\014\003\000\002\014\003\000\002\016\010\000\002" +
    "\015\005\000\002\017\006\000\002\020\004\000\002\020" +
    "\003\000\002\021\006\000\002\021\006\000\002\021\010" +
    "\000\002\021\006\000\002\022\003\000\002\022\005\000" +
    "\002\023\003\000\002\023\005\000\002\024\005\000\002" +
    "\055\004\000\002\055\003\000\002\056\012\000\002\057" +
    "\003\000\002\057\003\000\002\057\003\000\002\026\007" +
    "\000\002\027\004\000\002\027\003\000\002\030\006\000" +
    "\002\030\006\000\002\030\006\000\002\030\007\000\002" +
    "\030\004\000\002\045\004\000\002\045\003\000\002\031" +
    "\003\000\002\031\005\000\002\046\010\000\002\047\004" +
    "\000\002\047\003\000\002\050\011\000\002\050\005\000" +
    "\002\052\004\000\002\052\002\000\002\053\007\000\002" +
    "\032\007\000\002\033\004\000\002\033\003\000\002\034" +
    "\004\000\002\034\004\000\002\034\004\000\002\034\003" +
    "\000\002\034\003\000\002\035\005\000\002\035\006\000" +
    "\002\035\006\000\002\035\006\000\002\036\003\000\002" +
    "\044\004\000\002\044\004\000\002\044\004\000\002\044" +
    "\004\000\002\041\004\000\002\037\010\000\002\037\012" +
    "\000\002\040\010\000\002\042\003\000\002\042\005\000" +
    "\002\042\005\000\002\043\003\000\002\043\003\000\002" +
    "\043\003\000\002\043\003\000\002\043\003\000\002\043" +
    "\005\000\002\043\005\000\002\051\004\000\002\051\004" +
    "\000\002\051\004\000\002\051\004\000\002\051\010\000" +
    "\002\051\004\000\002\051\004\000\002\060\006\000\002" +
    "\061\005\000\002\061\003\000\002\061\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\374\000\004\004\005\001\002\000\004\002\376\001" +
    "\002\000\004\072\006\001\002\000\004\060\007\001\002" +
    "\000\004\005\011\001\002\000\006\005\011\061\371\001" +
    "\002\000\012\006\017\007\020\010\021\033\022\001\002" +
    "\000\006\005\ufffe\061\ufffe\001\002\000\006\005\ufffc\061" +
    "\ufffc\001\002\000\006\005\ufffb\061\ufffb\001\002\000\006" +
    "\005\ufffa\061\ufffa\001\002\000\006\005\ufffd\061\ufffd\001" +
    "\002\000\004\060\243\001\002\000\004\060\211\001\002" +
    "\000\004\060\206\001\002\000\004\060\023\001\002\000" +
    "\006\034\026\036\027\001\002\000\012\034\uffc7\036\uffc7" +
    "\040\uffc7\061\uffc7\001\002\000\012\034\026\036\027\040" +
    "\uffc3\061\uffc3\001\002\000\004\072\032\001\002\000\004" +
    "\072\030\001\002\000\004\066\031\001\002\000\012\034" +
    "\uffc5\036\uffc5\040\uffc5\061\uffc5\001\002\000\004\060\033" +
    "\001\002\000\004\035\034\001\002\000\004\072\035\001" +
    "\002\000\006\064\uffcb\066\uffcb\001\002\000\006\064\037" +
    "\066\040\001\002\000\004\072\042\001\002\000\004\061" +
    "\041\001\002\000\012\034\uffc6\036\uffc6\040\uffc6\061\uffc6" +
    "\001\002\000\006\064\uffca\066\uffca\001\002\000\006\040" +
    "\047\061\045\001\002\000\012\034\uffc8\036\uffc8\040\uffc8" +
    "\061\uffc8\001\002\000\006\005\uffc9\061\uffc9\001\002\000" +
    "\006\040\uffc4\061\uffc4\001\002\000\030\006\052\007\065" +
    "\037\057\046\056\047\053\052\061\053\060\062\055\072" +
    "\064\073\050\074\062\001\002\000\020\055\uffa7\056\uffa7" +
    "\057\uffa7\060\uffa7\063\uffa7\064\uffa7\066\uffa7\001\002\000" +
    "\020\055\uffa5\056\uffa5\057\uffa5\060\uffa5\063\uffa5\064\uffa5" +
    "\066\uffa5\001\002\000\030\006\052\007\065\037\057\046" +
    "\056\047\053\052\061\053\060\062\055\072\064\073\050" +
    "\074\062\001\002\000\030\006\052\007\065\037\057\046" +
    "\056\047\053\052\061\053\060\062\055\072\064\073\050" +
    "\074\062\001\002\000\020\055\uffa6\056\uffa6\057\uffa6\060" +
    "\uffa6\063\uffa6\064\uffa6\066\uffa6\001\002\000\030\006\052" +
    "\007\065\037\057\046\056\047\053\052\061\053\060\062" +
    "\055\072\064\073\050\074\062\001\002\000\030\006\052" +
    "\007\065\037\057\046\056\047\053\052\061\053\060\062" +
    "\055\072\064\073\050\074\062\001\002\000\004\062\174" +
    "\001\002\000\030\006\052\007\065\037\057\046\056\047" +
    "\053\052\061\053\060\062\055\072\064\073\050\074\062" +
    "\001\002\000\030\006\052\007\065\037\057\046\056\047" +
    "\053\052\061\053\060\062\055\072\064\073\050\074\062" +
    "\001\002\000\020\055\uffa8\056\uffa8\057\uffa8\060\uffa8\063" +
    "\uffa8\064\uffa8\066\uffa8\001\002\000\006\055\067\060\077" +
    "\001\002\000\022\055\uffa9\056\uffa9\057\uffa9\060\uffa9\062" +
    "\071\063\uffa9\064\uffa9\066\uffa9\001\002\000\030\006\052" +
    "\007\065\037\057\046\056\047\053\052\061\053\060\062" +
    "\055\072\064\073\050\074\062\001\002\000\020\055\067" +
    "\056\uff9c\057\uff9c\060\uff9c\063\uff9c\064\uff9c\066\uff9c\001" +
    "\002\000\030\006\052\007\065\037\057\046\056\047\053" +
    "\052\061\053\060\062\055\072\064\073\050\074\062\001" +
    "\002\000\020\055\uffa4\056\uffa4\057\uffa4\060\uffa4\063\uffa4" +
    "\064\uffa4\066\uffa4\001\002\000\034\006\052\007\065\037" +
    "\057\046\056\047\053\052\061\053\060\062\055\063\uff98" +
    "\064\uff98\072\064\073\050\074\062\001\002\000\010\055" +
    "\067\063\uff99\064\uff99\001\002\000\006\063\075\064\074" +
    "\001\002\000\030\006\052\007\065\037\057\046\056\047" +
    "\053\052\061\053\060\062\055\072\064\073\050\074\062" +
    "\001\002\000\020\055\uff9b\056\uff9b\057\uff9b\060\uff9b\063" +
    "\uff9b\064\uff9b\066\uff9b\001\002\000\010\055\067\063\uff9a" +
    "\064\uff9a\001\002\000\030\011\114\014\121\040\120\041" +
    "\115\042\106\043\103\044\100\045\102\050\104\051\117" +
    "\072\107\001\002\000\004\072\167\001\002\000\032\011" +
    "\114\014\121\040\120\041\115\042\106\043\103\044\100" +
    "\045\102\050\104\051\117\061\166\072\107\001\002\000" +
    "\030\006\052\007\065\037\057\046\056\047\053\052\061" +
    "\053\060\062\055\072\064\073\050\074\062\001\002\000" +
    "\004\072\162\001\002\000\030\006\052\007\065\037\057" +
    "\046\056\047\053\052\061\053\060\062\055\072\064\073" +
    "\050\074\062\001\002\000\040\011\uffbf\012\uffbf\013\uffbf" +
    "\014\uffbf\015\uffbf\040\uffbf\041\uffbf\042\uffbf\043\uffbf\044" +
    "\uffbf\045\uffbf\050\uffbf\051\uffbf\061\uffbf\072\uffbf\001\002" +
    "\000\030\006\052\007\065\037\057\046\056\047\053\052" +
    "\061\053\060\062\055\072\064\073\050\074\062\001\002" +
    "\000\004\054\156\001\002\000\004\066\155\001\002\000" +
    "\040\011\uffba\012\uffba\013\uffba\014\uffba\015\uffba\040\uffba" +
    "\041\uffba\042\uffba\043\uffba\044\uffba\045\uffba\050\uffba\051" +
    "\uffba\061\uffba\072\uffba\001\002\000\004\066\uffb5\001\002" +
    "\000\040\011\uffbb\012\uffbb\013\uffbb\014\uffbb\015\uffbb\040" +
    "\uffbb\041\uffbb\042\uffbb\043\uffbb\044\uffbb\045\uffbb\050\uffbb" +
    "\051\uffbb\061\uffbb\072\uffbb\001\002\000\004\062\145\001" +
    "\002\000\004\072\142\001\002\000\004\066\141\001\002" +
    "\000\030\006\052\007\065\037\057\046\056\047\053\052" +
    "\061\053\060\062\055\072\064\073\050\074\062\001\002" +
    "\000\030\006\052\007\065\037\057\046\056\047\053\052" +
    "\061\053\060\062\055\072\064\073\050\074\062\001\002" +
    "\000\004\062\124\001\002\000\004\066\123\001\002\000" +
    "\040\011\uffbd\012\uffbd\013\uffbd\014\uffbd\015\uffbd\040\uffbd" +
    "\041\uffbd\042\uffbd\043\uffbd\044\uffbd\045\uffbd\050\uffbd\051" +
    "\uffbd\061\uffbd\072\uffbd\001\002\000\030\006\052\007\065" +
    "\037\057\046\056\047\053\052\061\053\060\062\055\072" +
    "\064\073\050\074\062\001\002\000\012\055\067\056\134" +
    "\057\133\063\uffac\001\002\000\004\063\127\001\002\000" +
    "\030\011\114\014\121\040\120\041\115\042\106\043\103" +
    "\044\100\045\102\050\104\051\117\072\107\001\002\000" +
    "\032\011\114\014\121\015\132\040\120\041\115\042\106" +
    "\043\103\044\100\045\102\050\104\051\117\072\107\001" +
    "\002\000\040\011\uffc0\012\uffc0\013\uffc0\014\uffc0\015\uffc0" +
    "\040\uffc0\041\uffc0\042\uffc0\043\uffc0\044\uffc0\045\uffc0\050" +
    "\uffc0\051\uffc0\061\uffc0\072\uffc0\001\002\000\040\011\uffad" +
    "\012\uffad\013\uffad\014\uffad\015\uffad\040\uffad\041\uffad\042" +
    "\uffad\043\uffad\044\uffad\045\uffad\050\uffad\051\uffad\061\uffad" +
    "\072\uffad\001\002\000\030\006\052\007\065\037\057\046" +
    "\056\047\053\052\061\053\060\062\055\072\064\073\050" +
    "\074\062\001\002\000\030\006\052\007\065\037\057\046" +
    "\056\047\053\052\061\053\060\062\055\072\064\073\050" +
    "\074\062\001\002\000\006\055\067\063\uffab\001\002\000" +
    "\006\055\067\063\uffaa\001\002\000\006\055\067\066\uffb0" +
    "\001\002\000\006\055\067\066\uffb1\001\002\000\040\011" +
    "\uffbc\012\uffbc\013\uffbc\014\uffbc\015\uffbc\040\uffbc\041\uffbc" +
    "\042\uffbc\043\uffbc\044\uffbc\045\uffbc\050\uffbc\051\uffbc\061" +
    "\uffbc\072\uffbc\001\002\000\004\054\143\001\002\000\030" +
    "\006\052\007\065\037\057\046\056\047\053\052\061\053" +
    "\060\062\055\072\064\073\050\074\062\001\002\000\006" +
    "\055\067\066\uffb8\001\002\000\030\006\052\007\065\037" +
    "\057\046\056\047\053\052\061\053\060\062\055\072\064" +
    "\073\050\074\062\001\002\000\004\063\147\001\002\000" +
    "\030\011\114\014\121\040\120\041\115\042\106\043\103" +
    "\044\100\045\102\050\104\051\117\072\107\001\002\000" +
    "\034\011\114\012\151\013\152\014\121\040\120\041\115" +
    "\042\106\043\103\044\100\045\102\050\104\051\117\072" +
    "\107\001\002\000\030\011\114\014\121\040\120\041\115" +
    "\042\106\043\103\044\100\045\102\050\104\051\117\072" +
    "\107\001\002\000\040\011\uffaf\012\uffaf\013\uffaf\014\uffaf" +
    "\015\uffaf\040\uffaf\041\uffaf\042\uffaf\043\uffaf\044\uffaf\045" +
    "\uffaf\050\uffaf\051\uffaf\061\uffaf\072\uffaf\001\002\000\032" +
    "\011\114\013\154\014\121\040\120\041\115\042\106\043" +
    "\103\044\100\045\102\050\104\051\117\072\107\001\002" +
    "\000\040\011\uffae\012\uffae\013\uffae\014\uffae\015\uffae\040" +
    "\uffae\041\uffae\042\uffae\043\uffae\044\uffae\045\uffae\050\uffae" +
    "\051\uffae\061\uffae\072\uffae\001\002\000\040\011\uffbe\012" +
    "\uffbe\013\uffbe\014\uffbe\015\uffbe\040\uffbe\041\uffbe\042\uffbe" +
    "\043\uffbe\044\uffbe\045\uffbe\050\uffbe\051\uffbe\061\uffbe\072" +
    "\uffbe\001\002\000\030\006\052\007\065\037\057\046\056" +
    "\047\053\052\061\053\060\062\055\072\064\073\050\074" +
    "\062\001\002\000\006\055\067\066\uffb9\001\002\000\006" +
    "\055\067\066\uffb4\001\002\000\006\055\067\066\uffb2\001" +
    "\002\000\004\054\163\001\002\000\030\006\052\007\065" +
    "\037\057\046\056\047\053\052\061\053\060\062\055\072" +
    "\064\073\050\074\062\001\002\000\006\055\067\066\uffb6" +
    "\001\002\000\006\055\067\066\uffb3\001\002\000\006\040" +
    "\uffc2\061\uffc2\001\002\000\004\054\170\001\002\000\030" +
    "\006\052\007\065\037\057\046\056\047\053\052\061\053" +
    "\060\062\055\072\064\073\050\074\062\001\002\000\006" +
    "\055\067\066\uffb7\001\002\000\020\055\067\056\uffa0\057" +
    "\uffa0\060\uffa0\063\uffa0\064\uffa0\066\uffa0\001\002\000\020" +
    "\055\067\056\uff9f\057\uff9f\060\uff9f\063\uff9f\064\uff9f\066" +
    "\uff9f\001\002\000\030\006\052\007\065\037\057\046\056" +
    "\047\053\052\061\053\060\062\055\072\064\073\050\074" +
    "\062\001\002\000\006\055\067\064\176\001\002\000\030" +
    "\006\052\007\065\037\057\046\056\047\053\052\061\053" +
    "\060\062\055\072\064\073\050\074\062\001\002\000\006" +
    "\055\067\063\200\001\002\000\020\055\uff9e\056\uff9e\057" +
    "\uff9e\060\uff9e\063\uff9e\064\uff9e\066\uff9e\001\002\000\020" +
    "\055\067\056\uffa2\057\uffa2\060\uffa2\063\uffa2\064\uffa2\066" +
    "\uffa2\001\002\000\006\055\067\063\203\001\002\000\020" +
    "\055\uffa3\056\uffa3\057\uffa3\060\uffa3\063\uffa3\064\uffa3\066" +
    "\uffa3\001\002\000\020\055\067\056\uffa1\057\uffa1\060\uffa1" +
    "\063\uffa1\064\uffa1\066\uffa1\001\002\000\020\055\067\056" +
    "\uff9d\057\uff9d\060\uff9d\063\uff9d\064\uff9d\066\uff9d\001\002" +
    "\000\030\011\114\014\121\040\120\041\115\042\106\043" +
    "\103\044\100\045\102\050\104\051\117\072\107\001\002" +
    "\000\032\011\114\014\121\040\120\041\115\042\106\043" +
    "\103\044\100\045\102\050\104\051\117\061\210\072\107" +
    "\001\002\000\006\005\uffc1\061\uffc1\001\002\000\014\075" +
    "\213\076\214\077\216\100\220\101\217\001\002\000\016" +
    "\061\uffd3\075\uffd3\076\uffd3\077\uffd3\100\uffd3\101\uffd3\001" +
    "\002\000\004\065\240\001\002\000\004\065\235\001\002" +
    "\000\016\061\233\075\213\076\214\077\216\100\220\101" +
    "\217\001\002\000\004\066\232\001\002\000\004\065\227" +
    "\001\002\000\004\072\221\001\002\000\004\065\222\001" +
    "\002\000\004\072\223\001\002\000\006\066\uffcc\072\uffcc" +
    "\001\002\000\006\066\226\072\225\001\002\000\006\066" +
    "\uffcd\072\uffcd\001\002\000\016\061\uffcf\075\uffcf\076\uffcf" +
    "\077\uffcf\100\uffcf\101\uffcf\001\002\000\004\072\230\001" +
    "\002\000\004\066\231\001\002\000\016\061\uffd0\075\uffd0" +
    "\076\uffd0\077\uffd0\100\uffd0\101\uffd0\001\002\000\016\061" +
    "\uffce\075\uffce\076\uffce\077\uffce\100\uffce\101\uffce\001\002" +
    "\000\006\005\uffd5\061\uffd5\001\002\000\016\061\uffd4\075" +
    "\uffd4\076\uffd4\077\uffd4\100\uffd4\101\uffd4\001\002\000\004" +
    "\072\035\001\002\000\006\064\037\066\237\001\002\000" +
    "\016\061\uffd1\075\uffd1\076\uffd1\077\uffd1\100\uffd1\101\uffd1" +
    "\001\002\000\004\072\035\001\002\000\006\064\037\066" +
    "\242\001\002\000\016\061\uffd2\075\uffd2\076\uffd2\077\uffd2" +
    "\100\uffd2\101\uffd2\001\002\000\010\021\252\023\244\025" +
    "\251\001\002\000\004\060\352\001\002\000\012\021\ufff6" +
    "\023\ufff6\025\ufff6\061\ufff6\001\002\000\012\021\ufff7\023" +
    "\ufff7\025\ufff7\061\ufff7\001\002\000\012\021\ufff4\023\ufff4" +
    "\025\ufff4\061\ufff4\001\002\000\012\021\ufff5\023\ufff5\025" +
    "\ufff5\061\ufff5\001\002\000\004\060\275\001\002\000\004" +
    "\060\256\001\002\000\012\021\252\023\244\025\251\061" +
    "\254\001\002\000\006\005\ufff9\061\ufff9\001\002\000\012" +
    "\021\ufff8\023\ufff8\025\ufff8\061\ufff8\001\002\000\004\022" +
    "\261\001\002\000\006\022\ufff1\061\ufff1\001\002\000\006" +
    "\022\261\061\273\001\002\000\004\072\262\001\002\000" +
    "\004\054\263\001\002\000\004\067\264\001\002\000\004" +
    "\073\266\001\002\000\006\064\267\070\270\001\002\000" +
    "\006\064\uffef\070\uffef\001\002\000\004\073\272\001\002" +
    "\000\004\066\271\001\002\000\006\022\ufff0\061\ufff0\001" +
    "\002\000\006\064\uffee\070\uffee\001\002\000\012\021\ufff3" +
    "\023\ufff3\025\ufff3\061\ufff3\001\002\000\006\022\ufff2\061" +
    "\ufff2\001\002\000\012\026\301\027\302\030\300\031\276" +
    "\001\002\000\004\060\332\001\002\000\014\026\uffe5\027" +
    "\uffe5\030\uffe5\031\uffe5\061\uffe5\001\002\000\004\065\317" +
    "\001\002\000\004\065\311\001\002\000\004\065\306\001" +
    "\002\000\014\026\301\027\302\030\300\031\276\061\304" +
    "\001\002\000\012\021\uffe7\023\uffe7\025\uffe7\061\uffe7\001" +
    "\002\000\014\026\uffe6\027\uffe6\030\uffe6\031\uffe6\061\uffe6" +
    "\001\002\000\004\072\307\001\002\000\004\066\310\001" +
    "\002\000\014\026\uffe3\027\uffe3\030\uffe3\031\uffe3\061\uffe3" +
    "\001\002\000\004\072\312\001\002\000\006\064\uffe0\066" +
    "\uffe0\001\002\000\006\064\314\066\315\001\002\000\004" +
    "\072\316\001\002\000\014\026\uffe4\027\uffe4\030\uffe4\031" +
    "\uffe4\061\uffe4\001\002\000\006\064\uffdf\066\uffdf\001\002" +
    "\000\004\067\320\001\002\000\004\072\321\001\002\000" +
    "\004\054\330\001\002\000\006\064\uffde\070\uffde\001\002" +
    "\000\006\064\324\070\325\001\002\000\004\072\321\001" +
    "\002\000\004\066\326\001\002\000\014\026\uffe2\027\uffe2" +
    "\030\uffe2\031\uffe2\061\uffe2\001\002\000\006\064\uffdd\070" +
    "\uffdd\001\002\000\004\072\331\001\002\000\006\064\uffdc" +
    "\070\uffdc\001\002\000\004\062\334\001\002\000\006\061" +
    "\uffda\062\uffda\001\002\000\004\072\340\001\002\000\006" +
    "\061\336\062\334\001\002\000\014\026\uffe1\027\uffe1\030" +
    "\uffe1\031\uffe1\061\uffe1\001\002\000\006\061\uffdb\062\uffdb" +
    "\001\002\000\004\064\341\001\002\000\010\032\344\072" +
    "\343\073\345\001\002\000\004\063\346\001\002\000\004" +
    "\063\uffd8\001\002\000\004\063\uffd6\001\002\000\004\063" +
    "\uffd7\001\002\000\004\071\347\001\002\000\004\072\350" +
    "\001\002\000\004\066\351\001\002\000\006\061\uffd9\062" +
    "\uffd9\001\002\000\006\017\354\024\356\001\002\000\006" +
    "\017\354\061\367\001\002\000\004\072\365\001\002\000" +
    "\006\017\uffeb\061\uffeb\001\002\000\004\054\360\001\002" +
    "\000\006\017\uffea\061\uffea\001\002\000\004\067\361\001" +
    "\002\000\004\073\266\001\002\000\006\064\267\070\363" +
    "\001\002\000\004\066\364\001\002\000\006\017\uffe9\061" +
    "\uffe9\001\002\000\004\066\366\001\002\000\006\017\uffe8" +
    "\061\uffe8\001\002\000\012\021\uffed\023\uffed\025\uffed\061" +
    "\uffed\001\002\000\006\017\uffec\061\uffec\001\002\000\004" +
    "\102\373\001\002\000\006\005\uffff\061\uffff\001\002\000" +
    "\004\072\374\001\002\000\004\066\375\001\002\000\004" +
    "\002\000\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\374\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\003\007\004\011" +
    "\005\015\026\012\032\013\046\014\001\001\000\014\004" +
    "\371\005\015\026\012\032\013\046\014\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\047\024\050\023\001\001\000\002\001\001\000\006" +
    "\050\043\052\042\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\031\035\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\053\045\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\043\062\051\053\060\050\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\043\204\051\053\060\050" +
    "\001\001\000\010\043\203\051\053\060\050\001\001\000" +
    "\002\001\001\000\010\043\201\051\053\060\050\001\001" +
    "\000\010\043\200\051\053\060\050\001\001\000\002\001" +
    "\001\000\010\043\172\051\053\060\050\001\001\000\010" +
    "\043\171\051\053\060\050\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\043\065\051\053" +
    "\060\050\001\001\000\002\001\001\000\010\043\067\051" +
    "\053\060\050\001\001\000\002\001\001\000\012\043\071" +
    "\051\053\060\050\061\072\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\043\075\051\053\060\050\001\001" +
    "\000\002\001\001\000\002\001\001\000\022\033\100\034" +
    "\104\035\107\036\121\037\112\040\110\041\115\044\111" +
    "\001\001\000\002\001\001\000\020\034\130\035\107\036" +
    "\121\037\112\040\110\041\115\044\111\001\001\000\010" +
    "\043\164\051\053\060\050\001\001\000\002\001\001\000" +
    "\010\043\160\051\053\060\050\001\001\000\002\001\001" +
    "\000\010\043\157\051\053\060\050\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\043\137\051\053\060\050\001\001" +
    "\000\010\043\136\051\053\060\050\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\012\042\125" +
    "\043\124\051\053\060\050\001\001\000\002\001\001\000" +
    "\002\001\001\000\022\033\127\034\104\035\107\036\121" +
    "\037\112\040\110\041\115\044\111\001\001\000\020\034" +
    "\130\035\107\036\121\037\112\040\110\041\115\044\111" +
    "\001\001\000\002\001\001\000\002\001\001\000\010\043" +
    "\135\051\053\060\050\001\001\000\010\043\134\051\053" +
    "\060\050\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\043\143\051\053\060\050\001\001\000" +
    "\002\001\001\000\012\042\145\043\124\051\053\060\050" +
    "\001\001\000\002\001\001\000\022\033\147\034\104\035" +
    "\107\036\121\037\112\040\110\041\115\044\111\001\001" +
    "\000\020\034\130\035\107\036\121\037\112\040\110\041" +
    "\115\044\111\001\001\000\022\033\152\034\104\035\107" +
    "\036\121\037\112\040\110\041\115\044\111\001\001\000" +
    "\002\001\001\000\020\034\130\035\107\036\121\037\112" +
    "\040\110\041\115\044\111\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\043\156\051\053\060\050\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\043\163\051\053\060\050\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\043\170\051\053\060\050\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\043\174\051\053\060\050\001\001\000\002\001\001" +
    "\000\010\043\176\051\053\060\050\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\022\033\206\034\104\035\107\036\121\037\112\040\110" +
    "\041\115\044\111\001\001\000\020\034\130\035\107\036" +
    "\121\037\112\040\110\041\115\044\111\001\001\000\002" +
    "\001\001\000\006\027\214\030\211\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\030\233" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\045\223\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\031\235\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\031\240\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\006\252\007\245\010\244\013\247\017\246" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\007\254\010\244\013\247\017" +
    "\246\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\011\257\012\256\001\001\000\002\001\001\000\004\012" +
    "\273\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\025\264\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\020\302\021\276\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\021\304\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\022\312\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\023\322\024\321" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\024\326\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\055\334\056\332\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\056\336\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\057\341" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\014\352\015" +
    "\354\016\356\001\001\000\004\015\367\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\025\361\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintaxis$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintaxis$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintaxis$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    private Symbol s;

    public Symbol getS(){
        return this.s;
    }

    public void syntax_error(Symbol s){
        this.s = s;
        System.err.println("Errror sintáctico: "+ s.value);
    }   

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintaxis$actions {
  private final Sintaxis parser;

  /** Constructor */
  CUP$Sintaxis$actions(Sintaxis parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintaxis$do_action(
    int                        CUP$Sintaxis$act_num,
    java_cup.runtime.lr_parser CUP$Sintaxis$parser,
    java.util.Stack            CUP$Sintaxis$stack,
    int                        CUP$Sintaxis$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintaxis$result;

      /* select the action based on the action number */
      switch (CUP$Sintaxis$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 105: // argumentos ::= 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("argumentos",47, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 104: // argumentos ::= expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("argumentos",47, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 103: // argumentos ::= argumentos COMA expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("argumentos",47, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 102: // llamada_metodo ::= ID PAREN_ABRE argumentos PAREN_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("llamada_metodo",46, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // exp_llamada ::= ANALISIS_SINTACTICO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",39, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // exp_llamada ::= ANALISIS_LEXICO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",39, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // exp_llamada ::= GENERAR_TS PAREN_ABRE expresion COMA expresion PAREN_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",39, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // exp_llamada ::= COLUMNA expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",39, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // exp_llamada ::= LINEA expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",39, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // exp_llamada ::= VERIFICAR_ERRORES expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",39, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // exp_llamada ::= CARGAR_ARCHIVO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",39, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // expresion ::= PAREN_ABRE expresion PAREN_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // expresion ::= expresion OPE_ARITMETICO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // expresion ::= llamada_metodo 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // expresion ::= exp_llamada 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // expresion ::= CADENA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // expresion ::= NUMERO 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // expresion ::= ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // condicion ::= expresion OPE_LOGICO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion",32, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // condicion ::= expresion OPE_RELACIONAL expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion",32, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // condicion ::= expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion",32, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // ciclo_mientras ::= MIENTRAS PAREN_ABRE condicion PAREN_CIERRA instrucciones FIN_MIENTRAS 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("ciclo_mientras",30, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // condicion_si ::= SI PAREN_ABRE condicion PAREN_CIERRA instrucciones SINO instrucciones FIN_SI 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion_si",29, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-7)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // condicion_si ::= SI PAREN_ABRE condicion PAREN_CIERRA instrucciones FIN_SI 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion_si",29, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // llamada_reservada ::= CONSTRUIR_TABLA expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("llamada_reservada",31, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // llamada ::= LIMPIAR_ERRORES expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("llamada",34, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // llamada ::= VER_ERRORES expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("llamada",34, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // llamada ::= DIBUJAR expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("llamada",34, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // llamada ::= IMPRIMIR expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("llamada",34, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // funcion ::= llamada 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("funcion",28, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // asignacion ::= ARBOL ID OPE_ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("asignacion",27, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // asignacion ::= TOKENS ID OPE_ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("asignacion",27, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // asignacion ::= ENTRADA ID OPE_ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("asignacion",27, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // asignacion ::= ID OPE_ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("asignacion",27, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // instruccion ::= ciclo_mientras 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",26, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // instruccion ::= condicion_si 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",26, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // instruccion ::= llamada_reservada PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",26, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // instruccion ::= funcion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",26, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // instruccion ::= asignacion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",26, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // instrucciones ::= instruccion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instrucciones",25, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // instrucciones ::= instrucciones instruccion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instrucciones",25, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // seccion_principal ::= SECCION PRINCIPAL LLAVE_ABRE instrucciones LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion_principal",24, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // instruccion_tabla ::= CONSTRUIR_TABLA expresion LLAVE_ABRE instrucciones LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion_tabla",41, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // instrucciones_tabla ::= 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instrucciones_tabla",40, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // instrucciones_tabla ::= instrucciones_tabla instruccion_tabla 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instrucciones_tabla",40, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // decl_tabla ::= TABLA ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_tabla",38, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // decl_tabla ::= ESTRUCTURA_TABLA ID LLAVE_ABRE CAMPO ids PUNTO_COMA LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_tabla",38, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-6)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // contenido_tabla ::= decl_tabla 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("contenido_tabla",37, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // contenido_tabla ::= contenido_tabla decl_tabla 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("contenido_tabla",37, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // seccion_tabla ::= SECCION TABLA_SIMBOLOS LLAVE_ABRE contenido_tabla instrucciones_tabla LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion_tabla",36, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // ids ::= ids COMA ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("ids",23, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // ids ::= ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("ids",23, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // producciones ::= ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("producciones",35, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // producciones ::= producciones ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("producciones",35, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // declaracion_sintac ::= VACIO PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // declaracion_sintac ::= REGLA ID DOS_PUNTOS producciones PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // declaracion_sintac ::= INICIO DOS_PUNTOS ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // declaracion_sintac ::= NO_TERMINALES DOS_PUNTOS ids PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // declaracion_sintac ::= TERMINALES DOS_PUNTOS ids PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // lista_declaracion_sintac ::= declaracion_sintac 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_declaracion_sintac",21, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // lista_declaracion_sintac ::= lista_declaracion_sintac declaracion_sintac 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_declaracion_sintac",21, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // seccion_sintactico ::= SECCION ANALISIS_SINTACTICO LLAVE_ABRE lista_declaracion_sintac LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion_sintactico",20, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // entrada_transicion ::= OTRO 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("entrada_transicion",45, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // entrada_transicion ::= CADENA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("entrada_transicion",45, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // entrada_transicion ::= ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("entrada_transicion",45, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // transicion ::= PAREN_ABRE ID COMA entrada_transicion PAREN_CIERRA OPE_TRANSICION ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("transicion",44, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-7)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // lista_transiciones ::= transicion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_transiciones",43, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // lista_transiciones ::= lista_transiciones transicion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_transiciones",43, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // estado_final ::= ID OPE_ASIGNACION ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("estado_final",18, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // lista_estados_finales ::= lista_estados_finales COMA estado_final 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_estados_finales",17, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // lista_estados_finales ::= estado_final 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_estados_finales",17, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // lista_estados ::= lista_estados COMA ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_estados",16, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // lista_estados ::= ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_estados",16, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // decl_automata ::= TRANSICIONES LLAVE_ABRE lista_transiciones LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_automata",15, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // decl_automata ::= ESTADOS_FINALES DOS_PUNTOS CORCHETE_ABRE lista_estados_finales CORCHETE_CIERRA PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_automata",15, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // decl_automata ::= ESTADO_INICIAL DOS_PUNTOS ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_automata",15, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // decl_automata ::= ESTADOS DOS_PUNTOS lista_estados PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_automata",15, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // lista_decl_automata ::= decl_automata 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_automata",14, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // lista_decl_automata ::= lista_decl_automata decl_automata 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_automata",14, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // def_automata ::= EJECUTAR_AUTOMATA LLAVE_ABRE lista_decl_automata LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("def_automata",13, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // decl_token ::= TOKEN ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_token",11, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // decl_pal_res ::= PALABRAS_RESERVADAS OPE_ASIGNACION CORCHETE_ABRE lista_elementos CORCHETE_CIERRA PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_pal_res",12, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // lista_decl_tokens ::= decl_pal_res 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_tokens",10, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // lista_decl_tokens ::= decl_token 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_tokens",10, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // lista_decl_tokens ::= lista_decl_tokens decl_token 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_tokens",10, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // def_tokens ::= DEFINIR_TOKENS LLAVE_ABRE lista_decl_tokens LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("def_tokens",9, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // lista_elementos ::= lista_elementos COMA CADENA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_elementos",19, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // lista_elementos ::= CADENA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_elementos",19, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // conjunto_decl ::= CONJUNTO ID OPE_ASIGNACION CORCHETE_ABRE lista_elementos CORCHETE_CIERRA PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("conjunto_decl",8, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-6)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // lista_conjuntos ::= conjunto_decl 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_conjuntos",7, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // lista_conjuntos ::= lista_conjuntos conjunto_decl 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_conjuntos",7, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // def_alfabeto ::= DEFINIR_ALFABETO LLAVE_ABRE lista_conjuntos LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("def_alfabeto",6, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // declaracion_lex ::= def_automata 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_lex",5, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // declaracion_lex ::= def_tokens 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_lex",5, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // declaracion_lex ::= def_alfabeto 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_lex",5, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lista_declaracion_lex ::= declaracion_lex 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_declaracion_lex",4, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista_declaracion_lex ::= lista_declaracion_lex declaracion_lex 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_declaracion_lex",4, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // seccion_lexico ::= SECCION ANALISIS_LEXICO LLAVE_ABRE lista_declaracion_lex LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion_lexico",3, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // seccion ::= seccion_tabla 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion",2, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // seccion ::= seccion_principal 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion",2, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // seccion ::= seccion_sintactico 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion",2, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // seccion ::= seccion_lexico 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion",2, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_secciones ::= seccion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_secciones",1, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_secciones ::= lista_secciones seccion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_secciones",1, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= COMPILAR ID LLAVE_ABRE lista_secciones LLAVE_CIERRA EJECUTARPROG ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-7)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).value;
		RESULT = start_val;
              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintaxis$parser.done_parsing();
          return CUP$Sintaxis$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

