
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Dec 03 21:39:22 MST 2025
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPE_ASIGNACION = 42;
  public static final int NUMERO = 58;
  public static final int DIBUJAR = 35;
  public static final int CONJUNTO = 16;
  public static final int TRANSICIONES = 23;
  public static final int OTRO = 24;
  public static final int IMPRIMIR = 32;
  public static final int SI = 7;
  public static final int EJECUTARPROG = 64;
  public static final int LIMPIAR_ERRORES = 39;
  public static final int ESTADOS = 20;
  public static final int REGLA = 62;
  public static final int DOS_PUNTOS = 51;
  public static final int TOKENS = 34;
  public static final int PAREN_CIERRA = 49;
  public static final int TERMINALES = 59;
  public static final int FIN_SI = 9;
  public static final int PRINCIPAL = 6;
  public static final int OPE_TRANSICION = 55;
  public static final int EJECUTAR_AUTOMATA = 19;
  public static final int GENERAR_TS = 29;
  public static final int SINO = 8;
  public static final int IGNORAR = 12;
  public static final int CORCHETE_CIERRA = 54;
  public static final int MIENTRAS = 10;
  public static final int COMPILAR = 2;
  public static final int TOKEN = 13;
  public static final int CONSTRUIR_TABLA = 30;
  public static final int ANALISIS_LEXICO = 4;
  public static final int ID = 56;
  public static final int PUNTO_COMA = 52;
  public static final int EOF = 0;
  public static final int CAMPO = 27;
  public static final int PALABRAS_RESERVADAS = 18;
  public static final int error = 1;
  public static final int ESTADOS_FINALES = 22;
  public static final int COMA = 50;
  public static final int CADENA = 57;
  public static final int TABLA = 28;
  public static final int VERIFICAR_ERRORES = 37;
  public static final int LLAVE_ABRE = 46;
  public static final int FIN_MIENTRAS = 11;
  public static final int ARBOL = 33;
  public static final int DEFINIR_ALFABETO = 15;
  public static final int CORCHETE_ABRE = 53;
  public static final int ENTRADA = 31;
  public static final int ANALISIS_SINTACTICO = 5;
  public static final int ESTRUCTURA_TABLA = 26;
  public static final int PAREN_ABRE = 48;
  public static final int OPE_LOGICO = 45;
  public static final int DEFINIR_TOKENS = 17;
  public static final int VACIO = 61;
  public static final int CARGAR_ARCHIVO = 36;
  public static final int VER_ERRORES = 38;
  public static final int ESTADO_INICIAL = 21;
  public static final int LLAVE_CIERRA = 47;
  public static final int TABLA_SIMBOLOS = 25;
  public static final int INICIO = 63;
  public static final int OPE_RELACIONAL = 44;
  public static final int PATRON = 14;
  public static final int OPE_ARITMETICO = 43;
  public static final int LINEA = 40;
  public static final int SECCION = 3;
  public static final int COLUMNA = 41;
  public static final int NO_TERMINALES = 60;
}

