/* The following code was generated by JFlex 1.4.3 on 10/12/25 18:18 */

package codigo;
import static codigo.Tokens.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 10/12/25 18:18 from the specification file
 * <tt>C:/Users/alanc/OneDrive/Escritorio/compilercode-compilador/src/codigo/Lexer.flex</tt>
 */
class Lexer {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\10\2\0\1\3\22\0\1\3\1\45\1\6\1\11"+
    "\1\0\1\53\1\50\1\0\1\52\1\52\1\43\1\43\1\52\1\43"+
    "\1\5\1\43\12\4\1\52\1\52\1\46\1\44\1\47\2\0\17\2"+
    "\1\42\2\2\1\41\1\40\6\2\1\52\1\7\1\52\1\0\1\1"+
    "\1\0\1\23\1\34\1\26\1\33\1\20\1\16\1\30\1\37\1\13"+
    "\1\36\1\31\1\24\1\17\1\14\1\15\1\27\1\2\1\22\1\12"+
    "\1\21\1\35\1\32\1\2\1\25\2\2\1\52\1\51\1\52\103\0"+
    "\1\53\7\0\1\53\3\0\1\53\3\0\1\53\1\0\1\53\6\0"+
    "\1\53\1\0\1\53\4\0\1\53\7\0\1\53\3\0\1\53\3\0"+
    "\1\53\1\0\1\53\6\0\1\53\1\0\1\53\uff03\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\4\20\3\1\10\1\11\1\12\1\13\1\1\2\14"+
    "\1\6\1\2\2\15\1\16\1\7\1\0\1\17\34\3"+
    "\1\20\1\13\1\21\1\12\1\5\1\0\40\3\1\17"+
    "\47\3\1\17\2\3\1\17\45\3\1\17\127\3";

  private static int [] zzUnpackAction() {
    int [] result = new int[275];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\54\0\130\0\204\0\260\0\334\0\u0108\0\u0134"+
    "\0\u0160\0\u018c\0\u01b8\0\u01e4\0\u0210\0\u023c\0\u0268\0\u0294"+
    "\0\u02c0\0\u02ec\0\u0318\0\u0344\0\u0370\0\u039c\0\u03c8\0\u03f4"+
    "\0\u0420\0\u044c\0\u0478\0\u04a4\0\u04a4\0\u04d0\0\u04fc\0\54"+
    "\0\54\0\u0528\0\u0554\0\u0108\0\54\0\u0580\0\u05ac\0\u05d8"+
    "\0\u0604\0\u0630\0\u065c\0\u0688\0\u06b4\0\u06e0\0\u070c\0\u0738"+
    "\0\u0764\0\u0790\0\u07bc\0\u07e8\0\u0814\0\u0840\0\u086c\0\u0898"+
    "\0\u08c4\0\u08f0\0\u091c\0\u0948\0\u0974\0\u09a0\0\u09cc\0\u09f8"+
    "\0\u0a24\0\u0a50\0\u0a7c\0\u0aa8\0\u0ad4\0\54\0\54\0\54"+
    "\0\u0554\0\u0b00\0\u0b2c\0\u0b58\0\u0b84\0\u0bb0\0\u0bdc\0\u0c08"+
    "\0\u0c34\0\u0c60\0\u0c8c\0\u0cb8\0\u0ce4\0\u0d10\0\u0d3c\0\u0d68"+
    "\0\u0d94\0\u0dc0\0\u0dec\0\u0e18\0\u0e44\0\u0e70\0\u0e9c\0\u0ec8"+
    "\0\u0ef4\0\u0f20\0\u0f4c\0\u0f78\0\u0fa4\0\u0fd0\0\u0ffc\0\u1028"+
    "\0\u1054\0\u1080\0\204\0\u10ac\0\u10d8\0\u1104\0\u1130\0\u115c"+
    "\0\u1188\0\u11b4\0\u11e0\0\u120c\0\u1238\0\u1264\0\u1290\0\u12bc"+
    "\0\u12e8\0\u1314\0\u1340\0\u136c\0\u1398\0\u13c4\0\u13f0\0\u141c"+
    "\0\u1448\0\u1474\0\u14a0\0\u14cc\0\u14f8\0\u1524\0\u1550\0\u157c"+
    "\0\u15a8\0\u15d4\0\u1600\0\u162c\0\u1658\0\u1684\0\u16b0\0\u16dc"+
    "\0\u1708\0\u1734\0\u1760\0\u178c\0\u17b8\0\u17e4\0\u1810\0\u183c"+
    "\0\u1868\0\u1894\0\u18c0\0\u18ec\0\u1918\0\u1944\0\u1970\0\u199c"+
    "\0\u19c8\0\u19f4\0\u1a20\0\u1a4c\0\u1a78\0\u1aa4\0\u1ad0\0\u1afc"+
    "\0\u1b28\0\u1b54\0\u1b80\0\u1bac\0\u1bd8\0\u1c04\0\u1c30\0\u1c5c"+
    "\0\u1c88\0\u1cb4\0\u1ce0\0\u1d0c\0\u1d38\0\u1d64\0\u1d90\0\u1dbc"+
    "\0\u1760\0\u1de8\0\u1e14\0\u1e40\0\u1e6c\0\u1e98\0\u1ec4\0\u1ef0"+
    "\0\u1f1c\0\u1f48\0\u1f74\0\u1fa0\0\u1fcc\0\u1ff8\0\u2024\0\u2050"+
    "\0\u207c\0\u20a8\0\u20d4\0\u2100\0\u212c\0\u2158\0\u2184\0\u21b0"+
    "\0\u21dc\0\u2208\0\u2234\0\u2260\0\u228c\0\u22b8\0\u22e4\0\u2310"+
    "\0\u233c\0\u2368\0\u2394\0\u23c0\0\u23ec\0\u2418\0\u2444\0\u2470"+
    "\0\u249c\0\u24c8\0\u24f4\0\u2520\0\u254c\0\u2578\0\u25a4\0\u25d0"+
    "\0\u25fc\0\u2628\0\u2654\0\u2680\0\u26ac\0\u26d8\0\u2704\0\u2730"+
    "\0\u275c\0\u2788\0\u27b4\0\u27e0\0\u280c\0\u2838\0\u2864\0\u2890"+
    "\0\u28bc\0\u28e8\0\u2914\0\u2940\0\u296c\0\u2998\0\u29c4\0\u29f0"+
    "\0\u2a1c\0\u2a48\0\u2a74\0\u2aa0\0\u2acc\0\u2af8\0\u2b24\0\u2b50"+
    "\0\u2b7c\0\u2ba8\0\u2bd4\0\u2c00\0\u2c2c\0\u2c58\0\u2c84\0\u2cb0"+
    "\0\u2cdc\0\u2d08\0\u2d34";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[275];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\2"+
    "\1\5\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\21\1\22\1\23\1\24\1\4\1\25\1\26"+
    "\1\27\1\4\1\30\1\31\7\4\1\32\1\33\1\34"+
    "\2\35\1\36\1\37\1\40\1\41\55\0\1\42\1\4"+
    "\1\0\1\42\5\0\31\4\12\0\2\4\1\0\1\4"+
    "\5\0\31\4\14\0\1\5\4\0\1\5\44\0\2\42"+
    "\1\0\1\6\1\43\4\0\31\42\15\0\1\44\47\0"+
    "\6\10\1\45\1\46\1\47\43\10\10\11\1\0\43\11"+
    "\1\0\2\4\1\0\1\4\5\0\1\4\1\50\4\4"+
    "\1\51\22\4\12\0\2\4\1\0\1\4\5\0\2\4"+
    "\1\52\2\4\1\53\10\4\1\54\12\4\12\0\2\4"+
    "\1\0\1\4\5\0\3\4\1\55\25\4\12\0\2\4"+
    "\1\0\1\4\5\0\7\4\1\56\21\4\12\0\2\4"+
    "\1\0\1\4\5\0\1\4\1\57\27\4\12\0\2\4"+
    "\1\0\1\4\5\0\1\4\1\60\27\4\12\0\2\4"+
    "\1\0\1\4\5\0\1\61\1\4\1\62\21\4\1\63"+
    "\4\4\12\0\2\4\1\0\1\4\5\0\3\4\1\64"+
    "\2\4\1\65\1\4\1\66\1\67\17\4\12\0\2\4"+
    "\1\0\1\4\5\0\6\4\1\70\22\4\12\0\2\4"+
    "\1\0\1\4\5\0\2\4\1\71\5\4\1\72\20\4"+
    "\12\0\2\4\1\0\1\4\5\0\1\4\1\73\27\4"+
    "\12\0\2\4\1\0\1\4\5\0\3\4\1\74\5\4"+
    "\1\75\17\4\12\0\2\4\1\0\1\4\5\0\10\4"+
    "\1\76\1\77\17\4\12\0\2\4\1\0\1\4\5\0"+
    "\6\4\1\100\22\4\12\0\2\4\1\0\1\4\5\0"+
    "\6\4\1\101\2\4\1\102\17\4\12\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\103\4\4\1\104\22\4\12\0"+
    "\2\105\7\0\31\105\12\0\2\105\7\0\31\105\1\0"+
    "\1\106\2\0\1\107\5\0\2\105\7\0\31\105\1\0"+
    "\1\106\10\0\2\105\7\0\31\105\5\0\1\110\54\0"+
    "\1\110\3\0\2\42\1\0\1\42\5\0\31\42\15\0"+
    "\1\111\47\0\6\10\1\47\1\10\1\0\43\10\6\47"+
    "\1\45\1\112\44\47\1\0\2\4\1\0\1\4\5\0"+
    "\2\4\1\113\26\4\12\0\2\4\1\0\1\4\5\0"+
    "\14\4\1\114\14\4\12\0\2\4\1\0\1\4\5\0"+
    "\1\4\1\102\27\4\12\0\2\4\1\0\1\4\5\0"+
    "\15\4\1\115\13\4\12\0\2\4\1\0\1\4\5\0"+
    "\2\4\1\116\26\4\12\0\1\117\1\4\1\0\1\4"+
    "\5\0\31\4\12\0\2\4\1\0\1\4\5\0\10\4"+
    "\1\113\20\4\12\0\2\4\1\0\1\4\5\0\2\4"+
    "\1\120\26\4\12\0\2\4\1\0\1\4\5\0\6\4"+
    "\1\121\22\4\12\0\2\4\1\0\1\4\5\0\7\4"+
    "\1\122\21\4\12\0\2\4\1\0\1\4\5\0\7\4"+
    "\1\123\21\4\12\0\2\4\1\0\1\4\5\0\6\4"+
    "\1\124\22\4\12\0\2\4\1\0\1\4\5\0\17\4"+
    "\1\125\11\4\12\0\2\4\1\0\1\4\5\0\10\4"+
    "\1\126\20\4\12\0\2\4\1\0\1\4\5\0\11\4"+
    "\1\127\17\4\12\0\2\4\1\0\1\4\5\0\22\4"+
    "\1\130\6\4\12\0\2\4\1\0\1\4\5\0\16\4"+
    "\1\131\12\4\12\0\2\4\1\0\1\4\5\0\11\4"+
    "\1\132\17\4\12\0\2\4\1\0\1\4\5\0\22\4"+
    "\1\133\6\4\12\0\2\4\1\0\1\4\5\0\2\4"+
    "\1\134\2\4\1\135\23\4\12\0\2\4\1\0\1\4"+
    "\5\0\2\4\1\136\2\4\1\137\4\4\1\140\16\4"+
    "\12\0\2\4\1\0\1\4\5\0\5\4\1\141\2\4"+
    "\1\142\20\4\12\0\2\4\1\0\1\4\5\0\1\4"+
    "\1\143\27\4\12\0\2\4\1\0\1\4\5\0\7\4"+
    "\1\144\2\4\1\145\16\4\12\0\2\4\1\0\1\4"+
    "\5\0\2\4\1\146\26\4\12\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\147\20\4\12\0\2\4\1\0\1\4"+
    "\5\0\14\4\1\150\14\4\12\0\2\4\1\0\1\4"+
    "\5\0\22\4\1\151\6\4\12\0\2\4\1\0\1\4"+
    "\5\0\4\4\1\152\24\4\12\0\2\105\1\0\1\105"+
    "\5\0\31\105\11\0\10\47\1\0\43\47\1\0\2\4"+
    "\1\0\1\4\5\0\3\4\1\153\25\4\12\0\2\4"+
    "\1\0\1\4\5\0\14\4\1\154\14\4\12\0\2\4"+
    "\1\0\1\4\5\0\10\4\1\155\20\4\12\0\2\4"+
    "\1\0\1\4\5\0\3\4\1\156\25\4\12\0\2\4"+
    "\1\0\1\4\5\0\7\4\1\157\21\4\12\0\1\160"+
    "\1\4\1\0\1\4\5\0\31\4\12\0\2\4\1\0"+
    "\1\4\5\0\2\4\1\161\26\4\12\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\162\1\163\17\4\12\0\2\4"+
    "\1\0\1\4\5\0\10\4\1\164\20\4\12\0\2\4"+
    "\1\0\1\4\5\0\14\4\1\165\14\4\12\0\2\4"+
    "\1\0\1\4\5\0\6\4\1\166\22\4\12\0\2\4"+
    "\1\0\1\4\5\0\5\4\1\167\23\4\12\0\2\4"+
    "\1\0\1\4\5\0\2\4\1\170\26\4\12\0\2\4"+
    "\1\0\1\4\5\0\12\4\1\171\16\4\12\0\2\4"+
    "\1\0\1\4\5\0\12\4\1\172\16\4\12\0\2\4"+
    "\1\0\1\4\5\0\12\4\1\173\16\4\12\0\2\4"+
    "\1\0\1\4\5\0\3\4\1\174\25\4\12\0\2\4"+
    "\1\0\1\4\5\0\6\4\1\172\22\4\12\0\2\4"+
    "\1\0\1\4\5\0\15\4\1\175\13\4\12\0\2\4"+
    "\1\0\1\4\5\0\1\176\23\4\1\177\4\4\12\0"+
    "\2\4\1\0\1\4\5\0\15\4\1\200\13\4\12\0"+
    "\2\4\1\0\1\4\5\0\23\4\1\201\5\4\12\0"+
    "\2\4\1\0\1\4\5\0\15\4\1\113\13\4\12\0"+
    "\2\4\1\0\1\4\5\0\16\4\1\202\12\4\12\0"+
    "\2\4\1\0\1\4\5\0\2\4\1\203\26\4\12\0"+
    "\2\4\1\0\1\4\5\0\10\4\1\204\20\4\12\0"+
    "\2\4\1\0\1\4\5\0\11\4\1\205\17\4\12\0"+
    "\2\4\1\0\1\4\5\0\6\4\1\206\22\4\12\0"+
    "\1\207\1\4\1\0\1\4\5\0\1\4\1\210\27\4"+
    "\12\0\2\4\1\0\1\4\5\0\1\4\1\113\27\4"+
    "\12\0\2\4\1\0\1\4\5\0\23\4\1\211\5\4"+
    "\12\0\2\4\1\0\1\4\5\0\1\4\1\212\27\4"+
    "\12\0\2\4\1\0\1\4\5\0\1\4\1\204\27\4"+
    "\12\0\2\4\1\0\1\4\5\0\1\4\1\213\27\4"+
    "\12\0\2\4\1\0\1\4\5\0\10\4\1\214\20\4"+
    "\12\0\2\4\1\0\1\4\5\0\6\4\1\65\22\4"+
    "\12\0\2\4\1\0\1\4\5\0\1\215\4\4\1\17"+
    "\23\4\12\0\2\4\1\0\1\4\5\0\7\4\1\216"+
    "\21\4\12\0\2\4\1\0\1\4\5\0\23\4\1\217"+
    "\5\4\12\0\2\4\1\0\1\4\5\0\21\4\1\220"+
    "\7\4\12\0\2\4\1\0\1\4\5\0\11\4\1\221"+
    "\17\4\12\0\2\4\1\0\1\4\5\0\23\4\1\222"+
    "\5\4\12\0\2\4\1\0\1\4\5\0\2\4\1\223"+
    "\26\4\12\0\2\4\1\0\1\4\5\0\1\4\1\224"+
    "\27\4\12\0\2\4\1\0\1\4\5\0\1\225\30\4"+
    "\12\0\2\4\1\0\1\4\5\0\11\4\1\226\17\4"+
    "\12\0\2\4\1\0\1\4\5\0\11\4\1\153\17\4"+
    "\12\0\2\4\1\0\1\4\5\0\1\4\1\227\27\4"+
    "\12\0\2\4\1\0\1\4\5\0\12\4\1\153\16\4"+
    "\12\0\2\4\1\0\1\4\5\0\1\4\1\230\27\4"+
    "\12\0\2\4\1\0\1\4\5\0\7\4\1\231\21\4"+
    "\12\0\2\4\1\0\1\4\5\0\23\4\1\232\5\4"+
    "\12\0\2\4\1\0\1\4\5\0\1\4\1\233\27\4"+
    "\12\0\2\4\1\0\1\4\5\0\5\4\1\234\23\4"+
    "\12\0\2\4\1\0\1\4\5\0\11\4\1\235\17\4"+
    "\12\0\2\4\1\0\1\4\5\0\14\4\1\236\14\4"+
    "\12\0\2\4\1\0\1\4\5\0\3\4\1\237\25\4"+
    "\12\0\2\4\1\0\1\4\5\0\22\4\1\240\6\4"+
    "\12\0\2\4\1\0\1\4\5\0\10\4\1\241\20\4"+
    "\12\0\2\4\1\0\1\4\5\0\6\4\1\242\22\4"+
    "\12\0\2\4\1\0\1\4\5\0\4\4\1\243\24\4"+
    "\12\0\2\4\1\0\1\4\5\0\24\4\1\214\4\4"+
    "\12\0\2\4\1\0\1\4\5\0\2\4\1\244\26\4"+
    "\12\0\2\4\1\0\1\4\5\0\5\4\1\245\23\4"+
    "\12\0\2\4\1\0\1\4\5\0\11\4\1\246\17\4"+
    "\12\0\2\4\1\0\1\4\5\0\1\4\1\153\27\4"+
    "\12\0\2\4\1\0\1\4\5\0\10\4\1\247\20\4"+
    "\12\0\2\4\1\0\1\4\5\0\14\4\1\250\14\4"+
    "\12\0\2\4\1\0\1\4\5\0\3\4\1\251\25\4"+
    "\12\0\2\4\1\0\1\4\5\0\21\4\1\172\7\4"+
    "\12\0\2\4\1\0\1\4\5\0\7\4\1\252\21\4"+
    "\12\0\2\4\1\0\1\4\5\0\1\153\30\4\12\0"+
    "\2\4\1\0\1\4\5\0\2\4\1\253\26\4\12\0"+
    "\2\4\1\0\1\4\5\0\1\4\1\254\27\4\12\0"+
    "\1\255\1\4\1\0\1\4\5\0\31\4\12\0\2\4"+
    "\1\0\1\4\5\0\1\256\30\4\12\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\257\17\4\12\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\260\20\4\12\0\2\4\1\0"+
    "\1\4\5\0\2\4\1\261\26\4\12\0\2\4\1\0"+
    "\1\4\5\0\12\4\1\214\16\4\12\0\2\4\1\0"+
    "\1\4\5\0\2\4\1\172\26\4\12\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\262\20\4\12\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\263\27\4\12\0\2\4\1\0"+
    "\1\4\5\0\2\4\1\153\26\4\12\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\264\20\4\12\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\265\17\4\12\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\266\20\4\12\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\267\27\4\12\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\270\27\4\12\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\246\27\4\12\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\153\20\4\12\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\271\17\4\12\0\2\4\1\0"+
    "\1\4\5\0\7\4\1\272\21\4\12\0\1\273\1\4"+
    "\1\0\1\4\5\0\1\274\30\4\12\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\275\17\4\12\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\276\17\4\12\0\2\4\1\0"+
    "\1\4\5\0\14\4\1\277\14\4\12\0\2\4\1\0"+
    "\1\4\5\0\1\300\30\4\12\0\2\4\1\0\1\4"+
    "\5\0\1\4\1\301\27\4\12\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\302\20\4\12\0\2\4\1\0\1\4"+
    "\5\0\23\4\1\303\5\4\12\0\2\4\1\0\1\4"+
    "\5\0\7\4\1\113\21\4\12\0\1\304\1\4\1\0"+
    "\1\4\5\0\31\4\12\0\2\4\1\0\1\4\5\0"+
    "\15\4\1\305\13\4\12\0\2\4\1\0\1\4\5\0"+
    "\11\4\1\306\17\4\12\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\307\20\4\12\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\310\20\4\12\0\2\4\1\0\1\4\5\0"+
    "\14\4\1\230\14\4\12\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\311\20\4\12\0\2\4\1\0\1\4\5\0"+
    "\23\4\1\312\5\4\12\0\2\4\1\0\1\4\5\0"+
    "\1\4\1\313\27\4\12\0\1\314\1\4\1\0\1\4"+
    "\5\0\31\4\12\0\2\4\1\0\1\4\5\0\10\4"+
    "\1\315\20\4\12\0\2\4\1\0\1\4\5\0\12\4"+
    "\1\316\16\4\12\0\2\4\1\0\1\4\5\0\1\4"+
    "\1\317\27\4\12\0\2\4\1\0\1\4\5\0\1\4"+
    "\1\320\27\4\12\0\2\4\1\0\1\4\5\0\1\321"+
    "\30\4\12\0\1\207\1\4\1\0\1\4\5\0\31\4"+
    "\12\0\2\4\1\0\1\4\5\0\1\4\1\322\27\4"+
    "\12\0\2\4\1\0\1\4\5\0\11\4\1\323\17\4"+
    "\12\0\2\4\1\0\1\4\5\0\11\4\1\174\17\4"+
    "\12\0\2\4\1\0\1\4\5\0\1\324\30\4\12\0"+
    "\1\325\1\4\1\0\1\4\5\0\31\4\12\0\2\4"+
    "\1\0\1\4\5\0\3\4\1\326\25\4\12\0\1\327"+
    "\1\4\1\0\1\4\5\0\31\4\12\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\330\20\4\12\0\2\4\1\0"+
    "\1\4\5\0\2\4\1\331\26\4\12\0\2\4\1\0"+
    "\1\4\5\0\4\4\1\167\24\4\12\0\1\332\1\4"+
    "\1\0\1\4\5\0\30\4\1\333\12\0\2\4\1\0"+
    "\1\4\5\0\6\4\1\271\22\4\12\0\2\4\1\0"+
    "\1\4\5\0\3\4\1\334\25\4\12\0\2\4\1\0"+
    "\1\4\5\0\5\4\1\335\23\4\12\0\1\336\1\4"+
    "\1\0\1\4\5\0\31\4\12\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\337\20\4\12\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\340\20\4\12\0\1\341\1\4\1\0"+
    "\1\4\5\0\31\4\12\0\2\4\1\0\1\4\5\0"+
    "\26\4\1\342\2\4\12\0\2\4\1\0\1\4\5\0"+
    "\10\4\1\316\20\4\12\0\2\4\1\0\1\4\5\0"+
    "\7\4\1\343\1\4\1\344\17\4\12\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\337\17\4\12\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\345\27\4\12\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\346\17\4\12\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\347\20\4\12\0\2\4\1\0"+
    "\1\4\5\0\2\4\1\316\26\4\12\0\2\4\1\0"+
    "\1\4\5\0\22\4\1\350\6\4\12\0\2\4\1\0"+
    "\1\4\5\0\1\351\11\4\1\352\16\4\12\0\1\353"+
    "\1\4\1\0\1\4\5\0\31\4\12\0\2\4\1\0"+
    "\1\4\5\0\14\4\1\354\14\4\12\0\2\4\1\0"+
    "\1\4\5\0\10\4\1\355\20\4\12\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\356\17\4\12\0\2\4\1\0"+
    "\1\4\5\0\3\4\1\357\25\4\12\0\2\4\1\0"+
    "\1\4\5\0\12\4\1\360\16\4\12\0\2\4\1\0"+
    "\1\4\5\0\14\4\1\361\14\4\12\0\2\4\1\0"+
    "\1\4\5\0\23\4\1\362\5\4\12\0\2\4\1\0"+
    "\1\4\5\0\3\4\1\363\25\4\12\0\2\4\1\0"+
    "\1\4\5\0\3\4\1\364\25\4\12\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\365\27\4\12\0\2\4\1\0"+
    "\1\4\5\0\6\4\1\366\22\4\12\0\2\4\1\0"+
    "\1\4\5\0\7\4\1\367\21\4\12\0\2\4\1\0"+
    "\1\4\5\0\25\4\1\370\3\4\12\0\2\4\1\0"+
    "\1\4\5\0\6\4\1\371\22\4\12\0\2\4\1\0"+
    "\1\4\5\0\22\4\1\372\6\4\12\0\2\4\1\0"+
    "\1\4\5\0\17\4\1\373\11\4\12\0\2\4\1\0"+
    "\1\4\5\0\4\4\1\374\24\4\12\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\305\27\4\12\0\2\4\1\0"+
    "\1\4\5\0\7\4\1\375\21\4\12\0\2\4\1\0"+
    "\1\4\5\0\16\4\1\153\12\4\12\0\2\4\1\0"+
    "\1\4\5\0\12\4\1\376\16\4\12\0\2\4\1\0"+
    "\1\4\5\0\2\4\1\377\26\4\12\0\2\4\1\0"+
    "\1\4\5\0\13\4\1\u0100\15\4\12\0\2\4\1\0"+
    "\1\4\5\0\11\4\1\u0101\17\4\12\0\2\4\1\0"+
    "\1\4\5\0\1\4\1\u0102\27\4\12\0\2\4\1\0"+
    "\1\4\5\0\1\u0103\30\4\12\0\2\4\1\0\1\4"+
    "\5\0\12\4\1\u0104\16\4\12\0\2\4\1\0\1\4"+
    "\5\0\6\4\1\u0105\22\4\12\0\2\4\1\0\1\4"+
    "\5\0\11\4\1\u0106\17\4\12\0\2\4\1\0\1\4"+
    "\5\0\3\4\1\u0107\25\4\12\0\2\4\1\0\1\4"+
    "\5\0\3\4\1\271\25\4\12\0\2\4\1\0\1\4"+
    "\5\0\7\4\1\u0108\21\4\12\0\2\4\1\0\1\4"+
    "\5\0\1\4\1\u0109\27\4\12\0\2\4\1\0\1\4"+
    "\5\0\22\4\1\131\6\4\12\0\2\4\1\0\1\4"+
    "\5\0\20\4\1\113\10\4\12\0\2\4\1\0\1\4"+
    "\5\0\6\4\1\u010a\22\4\12\0\2\4\1\0\1\4"+
    "\5\0\11\4\1\u010b\17\4\12\0\2\4\1\0\1\4"+
    "\5\0\2\4\1\271\26\4\12\0\2\4\1\0\1\4"+
    "\5\0\22\4\1\u010c\6\4\12\0\2\4\1\0\1\4"+
    "\5\0\5\4\1\u010d\23\4\12\0\2\4\1\0\1\4"+
    "\5\0\11\4\1\u010e\17\4\12\0\2\4\1\0\1\4"+
    "\5\0\14\4\1\113\14\4\12\0\2\4\1\0\1\4"+
    "\5\0\10\4\1\u010f\20\4\12\0\2\4\1\0\1\4"+
    "\5\0\27\4\1\300\1\4\12\0\2\4\1\0\1\4"+
    "\5\0\6\4\1\261\22\4\12\0\2\4\1\0\1\4"+
    "\5\0\11\4\1\u0110\17\4\12\0\2\4\1\0\1\4"+
    "\5\0\14\4\1\u0111\14\4\12\0\2\4\1\0\1\4"+
    "\5\0\20\4\1\u0112\10\4\12\0\2\4\1\0\1\4"+
    "\5\0\7\4\1\172\21\4\12\0\2\4\1\0\1\4"+
    "\5\0\7\4\1\u0100\21\4\12\0\2\4\1\0\1\4"+
    "\5\0\11\4\1\u0113\17\4\12\0\2\4\1\0\1\4"+
    "\5\0\21\4\1\247\7\4\11\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[11616];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\35\1\2\11\3\1\1\11\1\1\1\0"+
    "\36\1\3\11\1\1\1\0\311\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[275];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private final TablaSimbolos tablaSimbolos = new TablaSimbolos();
    private final TablaFunciones tablaFunciones = new TablaFunciones();

    public TablaSimbolos getTablaSimbolos() {
        return this.tablaSimbolos;
    }

    public TablaFunciones getTablaFunciones() { 
        return this.tablaFunciones;
    }

    private Tokens token(String lex, String comp, int li, int c){
        return new Tokens(lex, comp, li+1, c+1); 
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 196) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public Tokens yylex() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 10: 
          { return token(yytext(),"OPE_LOGICO",yyline,yycolumn);
          }
        case 18: break;
        case 9: 
          { return token(yytext(),"OPE_ASIGNACION",yyline,yycolumn);
          }
        case 19: break;
        case 17: 
          { return token(yytext(),"OPE_TRANSICION",yyline,yycolumn);
          }
        case 20: break;
        case 12: 
          { return token(yytext(),"DELIMITADOR",yyline,yycolumn);
          }
        case 21: break;
        case 15: 
          { return token(yytext(),"PALABRA_RESERVADA",yyline,yycolumn);
          }
        case 22: break;
        case 13: 
          { return token(yytext(),"ERROR_NUMERO_MALFORMADO",yyline,yycolumn);
          }
        case 23: break;
        case 7: 
          { return token(yytext(),"ERROR_CADENA_NO_CERRADA",yyline,yycolumn);
          }
        case 24: break;
        case 1: 
          { return token(yytext(),"ERROR_CARACTER_INVALIDO",yyline,yycolumn);
          }
        case 25: break;
        case 14: 
          { return token(yytext(),"CADENA",yyline,yycolumn);
          }
        case 26: break;
        case 6: 
          { return token(yytext(), "ERROR", yyline, yycolumn);
          }
        case 27: break;
        case 3: 
          { // Revisa la "Tabla Fija"
        if (TablaPalabrasReservadas.esReservada(yytext())){
            return token(yytext(),"ERROR_IDENTIFICADOR_ES_PALABRA_RESERVADA",yyline,yycolumn);
        } else {
            // Si no es reservada, la registra en la "Tabla de identificadores"
            tablaSimbolos.registrarIdentificador(yytext(), yyline+1, yycolumn+1);
            return token(yytext(),"IDENTIFICADOR",yyline,yycolumn);
        }
          }
        case 28: break;
        case 2: 
          { return token(yytext(), "ERROR_IDENTIFICADOR_INVALIDO", yyline, yycolumn);
          }
        case 29: break;
        case 4: 
          { /* ignorar */
          }
        case 30: break;
        case 16: 
          { return token(yytext(), "ERROR_LEXICO", yyline, yycolumn);
          }
        case 31: break;
        case 5: 
          { return token(yytext(),"NUMERO",yyline,yycolumn);
          }
        case 32: break;
        case 8: 
          { return token(yytext(),"OPE_ARITMETICO",yyline,yycolumn);
          }
        case 33: break;
        case 11: 
          { return token(yytext(),"OPE_RELACIONAL",yyline,yycolumn);
          }
        case 34: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            return null;
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
