
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 07 17:45:12 MST 2025
//----------------------------------------------------

package codigo;

import java_cup.runtime.Symbol;
import codigo.TablaSimbolos;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Dec 07 17:45:12 MST 2025
  */
public class Sintaxis extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintaxis() {super();}

  /** Constructor which sets the default scanner. */
  public Sintaxis(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintaxis(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\150\000\002\002\004\000\002\002\012\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\005\007\000" +
    "\002\006\004\000\002\006\003\000\002\007\003\000\002" +
    "\007\003\000\002\007\003\000\002\010\006\000\002\011" +
    "\004\000\002\011\003\000\002\012\011\000\002\013\006" +
    "\000\002\014\004\000\002\014\003\000\002\014\003\000" +
    "\002\016\010\000\002\061\002\000\002\015\006\000\002" +
    "\017\006\000\002\020\004\000\002\020\003\000\002\021" +
    "\006\000\002\021\006\000\002\021\010\000\002\021\006" +
    "\000\002\022\003\000\002\022\005\000\002\023\003\000" +
    "\002\023\005\000\002\024\005\000\002\054\004\000\002" +
    "\054\003\000\002\055\012\000\002\056\003\000\002\056" +
    "\003\000\002\056\003\000\002\026\007\000\002\027\004" +
    "\000\002\027\003\000\002\030\006\000\002\030\006\000" +
    "\002\030\006\000\002\030\007\000\002\030\004\000\002" +
    "\044\004\000\002\044\003\000\002\031\003\000\002\031" +
    "\005\000\002\045\010\000\002\046\004\000\002\046\003" +
    "\000\002\047\011\000\002\047\005\000\002\051\004\000" +
    "\002\051\002\000\002\052\007\000\002\032\007\000\002" +
    "\033\004\000\002\033\003\000\002\034\004\000\002\034" +
    "\004\000\002\034\004\000\002\034\003\000\002\034\003" +
    "\000\002\035\005\000\002\035\006\000\002\035\006\000" +
    "\002\035\006\000\002\036\004\000\002\036\004\000\002" +
    "\036\004\000\002\036\004\000\002\041\004\000\002\037" +
    "\010\000\002\037\012\000\002\040\010\000\002\042\003" +
    "\000\002\042\005\000\002\042\005\000\002\043\003\000" +
    "\002\043\003\000\002\043\003\000\002\043\003\000\002" +
    "\043\003\000\002\043\005\000\002\043\005\000\002\050" +
    "\004\000\002\050\004\000\002\050\004\000\002\050\004" +
    "\000\002\050\010\000\002\050\004\000\002\050\004\000" +
    "\002\057\006\000\002\060\005\000\002\060\003\000\002" +
    "\060\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\371\000\004\004\005\001\002\000\004\002\373\001" +
    "\002\000\004\072\006\001\002\000\004\060\007\001\002" +
    "\000\004\005\011\001\002\000\006\005\011\061\366\001" +
    "\002\000\012\006\017\007\020\010\021\030\022\001\002" +
    "\000\006\005\ufffe\061\ufffe\001\002\000\006\005\ufffc\061" +
    "\ufffc\001\002\000\006\005\ufffb\061\ufffb\001\002\000\006" +
    "\005\ufffa\061\ufffa\001\002\000\006\005\ufffd\061\ufffd\001" +
    "\002\000\004\060\242\001\002\000\004\060\210\001\002" +
    "\000\004\060\205\001\002\000\004\060\023\001\002\000" +
    "\006\031\026\033\027\001\002\000\012\031\uffc8\033\uffc8" +
    "\035\uffc8\061\uffc8\001\002\000\012\031\026\033\027\035" +
    "\uffc4\061\uffc4\001\002\000\004\072\032\001\002\000\004" +
    "\072\030\001\002\000\004\066\031\001\002\000\012\031" +
    "\uffc6\033\uffc6\035\uffc6\061\uffc6\001\002\000\004\060\033" +
    "\001\002\000\004\032\034\001\002\000\004\072\035\001" +
    "\002\000\006\064\uffcc\066\uffcc\001\002\000\006\064\037" +
    "\066\040\001\002\000\004\072\042\001\002\000\004\061" +
    "\041\001\002\000\012\031\uffc7\033\uffc7\035\uffc7\061\uffc7" +
    "\001\002\000\006\064\uffcb\066\uffcb\001\002\000\012\031" +
    "\uffc9\033\uffc9\035\uffc9\061\uffc9\001\002\000\006\035\047" +
    "\061\045\001\002\000\006\005\uffca\061\uffca\001\002\000" +
    "\006\035\uffc5\061\uffc5\001\002\000\030\006\052\007\065" +
    "\034\057\046\056\047\053\052\060\053\061\062\055\072" +
    "\064\073\050\074\062\001\002\000\020\055\uffa9\056\uffa9" +
    "\057\uffa9\060\uffa9\063\uffa9\064\uffa9\066\uffa9\001\002\000" +
    "\020\055\uffa7\056\uffa7\057\uffa7\060\uffa7\063\uffa7\064\uffa7" +
    "\066\uffa7\001\002\000\030\006\052\007\065\034\057\046" +
    "\056\047\053\052\060\053\061\062\055\072\064\073\050" +
    "\074\062\001\002\000\030\006\052\007\065\034\057\046" +
    "\056\047\053\052\060\053\061\062\055\072\064\073\050" +
    "\074\062\001\002\000\020\055\uffa8\056\uffa8\057\uffa8\060" +
    "\uffa8\063\uffa8\064\uffa8\066\uffa8\001\002\000\030\006\052" +
    "\007\065\034\057\046\056\047\053\052\060\053\061\062" +
    "\055\072\064\073\050\074\062\001\002\000\030\006\052" +
    "\007\065\034\057\046\056\047\053\052\060\053\061\062" +
    "\055\072\064\073\050\074\062\001\002\000\004\062\173" +
    "\001\002\000\030\006\052\007\065\034\057\046\056\047" +
    "\053\052\060\053\061\062\055\072\064\073\050\074\062" +
    "\001\002\000\030\006\052\007\065\034\057\046\056\047" +
    "\053\052\060\053\061\062\055\072\064\073\050\074\062" +
    "\001\002\000\020\055\uffaa\056\uffaa\057\uffaa\060\uffaa\063" +
    "\uffaa\064\uffaa\066\uffaa\001\002\000\006\055\067\060\077" +
    "\001\002\000\022\055\uffab\056\uffab\057\uffab\060\uffab\062" +
    "\071\063\uffab\064\uffab\066\uffab\001\002\000\030\006\052" +
    "\007\065\034\057\046\056\047\053\052\060\053\061\062" +
    "\055\072\064\073\050\074\062\001\002\000\020\055\067" +
    "\056\uff9e\057\uff9e\060\uff9e\063\uff9e\064\uff9e\066\uff9e\001" +
    "\002\000\030\006\052\007\065\034\057\046\056\047\053" +
    "\052\060\053\061\062\055\072\064\073\050\074\062\001" +
    "\002\000\020\055\uffa6\056\uffa6\057\uffa6\060\uffa6\063\uffa6" +
    "\064\uffa6\066\uffa6\001\002\000\034\006\052\007\065\034" +
    "\057\046\056\047\053\052\060\053\061\062\055\063\uff9a" +
    "\064\uff9a\072\064\073\050\074\062\001\002\000\010\055" +
    "\067\063\uff9b\064\uff9b\001\002\000\006\063\075\064\074" +
    "\001\002\000\030\006\052\007\065\034\057\046\056\047" +
    "\053\052\060\053\061\062\055\072\064\073\050\074\062" +
    "\001\002\000\020\055\uff9d\056\uff9d\057\uff9d\060\uff9d\063" +
    "\uff9d\064\uff9d\066\uff9d\001\002\000\010\055\067\063\uff9c" +
    "\064\uff9c\001\002\000\030\011\113\014\120\035\116\036" +
    "\114\037\106\040\103\042\100\045\102\050\104\051\117" +
    "\072\107\001\002\000\004\072\166\001\002\000\032\011" +
    "\113\014\120\035\116\036\114\037\106\040\103\042\100" +
    "\045\102\050\104\051\117\061\165\072\107\001\002\000" +
    "\030\006\052\007\065\034\057\046\056\047\053\052\060" +
    "\053\061\062\055\072\064\073\050\074\062\001\002\000" +
    "\004\072\161\001\002\000\030\006\052\007\065\034\057" +
    "\046\056\047\053\052\060\053\061\062\055\072\064\073" +
    "\050\074\062\001\002\000\040\011\uffc0\012\uffc0\013\uffc0" +
    "\014\uffc0\015\uffc0\035\uffc0\036\uffc0\037\uffc0\040\uffc0\042" +
    "\uffc0\045\uffc0\050\uffc0\051\uffc0\061\uffc0\072\uffc0\001\002" +
    "\000\030\006\052\007\065\034\057\046\056\047\053\052" +
    "\060\053\061\062\055\072\064\073\050\074\062\001\002" +
    "\000\004\054\155\001\002\000\004\066\154\001\002\000" +
    "\040\011\uffbb\012\uffbb\013\uffbb\014\uffbb\015\uffbb\035\uffbb" +
    "\036\uffbb\037\uffbb\040\uffbb\042\uffbb\045\uffbb\050\uffbb\051" +
    "\uffbb\061\uffbb\072\uffbb\001\002\000\040\011\uffbc\012\uffbc" +
    "\013\uffbc\014\uffbc\015\uffbc\035\uffbc\036\uffbc\037\uffbc\040" +
    "\uffbc\042\uffbc\045\uffbc\050\uffbc\051\uffbc\061\uffbc\072\uffbc" +
    "\001\002\000\004\062\144\001\002\000\004\072\141\001" +
    "\002\000\004\066\140\001\002\000\030\006\052\007\065" +
    "\034\057\046\056\047\053\052\060\053\061\062\055\072" +
    "\064\073\050\074\062\001\002\000\030\006\052\007\065" +
    "\034\057\046\056\047\053\052\060\053\061\062\055\072" +
    "\064\073\050\074\062\001\002\000\004\062\123\001\002" +
    "\000\004\066\122\001\002\000\040\011\uffbe\012\uffbe\013" +
    "\uffbe\014\uffbe\015\uffbe\035\uffbe\036\uffbe\037\uffbe\040\uffbe" +
    "\042\uffbe\045\uffbe\050\uffbe\051\uffbe\061\uffbe\072\uffbe\001" +
    "\002\000\030\006\052\007\065\034\057\046\056\047\053" +
    "\052\060\053\061\062\055\072\064\073\050\074\062\001" +
    "\002\000\012\055\067\056\133\057\132\063\uffae\001\002" +
    "\000\004\063\126\001\002\000\030\011\113\014\120\035" +
    "\116\036\114\037\106\040\103\042\100\045\102\050\104" +
    "\051\117\072\107\001\002\000\032\011\113\014\120\015" +
    "\131\035\116\036\114\037\106\040\103\042\100\045\102" +
    "\050\104\051\117\072\107\001\002\000\040\011\uffc1\012" +
    "\uffc1\013\uffc1\014\uffc1\015\uffc1\035\uffc1\036\uffc1\037\uffc1" +
    "\040\uffc1\042\uffc1\045\uffc1\050\uffc1\051\uffc1\061\uffc1\072" +
    "\uffc1\001\002\000\040\011\uffaf\012\uffaf\013\uffaf\014\uffaf" +
    "\015\uffaf\035\uffaf\036\uffaf\037\uffaf\040\uffaf\042\uffaf\045" +
    "\uffaf\050\uffaf\051\uffaf\061\uffaf\072\uffaf\001\002\000\030" +
    "\006\052\007\065\034\057\046\056\047\053\052\060\053" +
    "\061\062\055\072\064\073\050\074\062\001\002\000\030" +
    "\006\052\007\065\034\057\046\056\047\053\052\060\053" +
    "\061\062\055\072\064\073\050\074\062\001\002\000\006" +
    "\055\067\063\uffad\001\002\000\006\055\067\063\uffac\001" +
    "\002\000\006\055\067\066\uffb3\001\002\000\006\055\067" +
    "\066\uffb2\001\002\000\040\011\uffbd\012\uffbd\013\uffbd\014" +
    "\uffbd\015\uffbd\035\uffbd\036\uffbd\037\uffbd\040\uffbd\042\uffbd" +
    "\045\uffbd\050\uffbd\051\uffbd\061\uffbd\072\uffbd\001\002\000" +
    "\004\054\142\001\002\000\030\006\052\007\065\034\057" +
    "\046\056\047\053\052\060\053\061\062\055\072\064\073" +
    "\050\074\062\001\002\000\006\055\067\066\uffb9\001\002" +
    "\000\030\006\052\007\065\034\057\046\056\047\053\052" +
    "\060\053\061\062\055\072\064\073\050\074\062\001\002" +
    "\000\004\063\146\001\002\000\030\011\113\014\120\035" +
    "\116\036\114\037\106\040\103\042\100\045\102\050\104" +
    "\051\117\072\107\001\002\000\034\011\113\012\150\013" +
    "\151\014\120\035\116\036\114\037\106\040\103\042\100" +
    "\045\102\050\104\051\117\072\107\001\002\000\030\011" +
    "\113\014\120\035\116\036\114\037\106\040\103\042\100" +
    "\045\102\050\104\051\117\072\107\001\002\000\040\011" +
    "\uffb1\012\uffb1\013\uffb1\014\uffb1\015\uffb1\035\uffb1\036\uffb1" +
    "\037\uffb1\040\uffb1\042\uffb1\045\uffb1\050\uffb1\051\uffb1\061" +
    "\uffb1\072\uffb1\001\002\000\032\011\113\013\153\014\120" +
    "\035\116\036\114\037\106\040\103\042\100\045\102\050" +
    "\104\051\117\072\107\001\002\000\040\011\uffb0\012\uffb0" +
    "\013\uffb0\014\uffb0\015\uffb0\035\uffb0\036\uffb0\037\uffb0\040" +
    "\uffb0\042\uffb0\045\uffb0\050\uffb0\051\uffb0\061\uffb0\072\uffb0" +
    "\001\002\000\040\011\uffbf\012\uffbf\013\uffbf\014\uffbf\015" +
    "\uffbf\035\uffbf\036\uffbf\037\uffbf\040\uffbf\042\uffbf\045\uffbf" +
    "\050\uffbf\051\uffbf\061\uffbf\072\uffbf\001\002\000\030\006" +
    "\052\007\065\034\057\046\056\047\053\052\060\053\061" +
    "\062\055\072\064\073\050\074\062\001\002\000\006\055" +
    "\067\066\uffba\001\002\000\006\055\067\066\uffb6\001\002" +
    "\000\006\055\067\066\uffb4\001\002\000\004\054\162\001" +
    "\002\000\030\006\052\007\065\034\057\046\056\047\053" +
    "\052\060\053\061\062\055\072\064\073\050\074\062\001" +
    "\002\000\006\055\067\066\uffb7\001\002\000\006\055\067" +
    "\066\uffb5\001\002\000\006\035\uffc3\061\uffc3\001\002\000" +
    "\004\054\167\001\002\000\030\006\052\007\065\034\057" +
    "\046\056\047\053\052\060\053\061\062\055\072\064\073" +
    "\050\074\062\001\002\000\006\055\067\066\uffb8\001\002" +
    "\000\020\055\067\056\uffa1\057\uffa1\060\uffa1\063\uffa1\064" +
    "\uffa1\066\uffa1\001\002\000\020\055\067\056\uffa2\057\uffa2" +
    "\060\uffa2\063\uffa2\064\uffa2\066\uffa2\001\002\000\030\006" +
    "\052\007\065\034\057\046\056\047\053\052\060\053\061" +
    "\062\055\072\064\073\050\074\062\001\002\000\006\055" +
    "\067\064\175\001\002\000\030\006\052\007\065\034\057" +
    "\046\056\047\053\052\060\053\061\062\055\072\064\073" +
    "\050\074\062\001\002\000\006\055\067\063\177\001\002" +
    "\000\020\055\uffa0\056\uffa0\057\uffa0\060\uffa0\063\uffa0\064" +
    "\uffa0\066\uffa0\001\002\000\020\055\067\056\uffa4\057\uffa4" +
    "\060\uffa4\063\uffa4\064\uffa4\066\uffa4\001\002\000\006\055" +
    "\067\063\202\001\002\000\020\055\uffa5\056\uffa5\057\uffa5" +
    "\060\uffa5\063\uffa5\064\uffa5\066\uffa5\001\002\000\020\055" +
    "\067\056\uffa3\057\uffa3\060\uffa3\063\uffa3\064\uffa3\066\uffa3" +
    "\001\002\000\020\055\067\056\uff9f\057\uff9f\060\uff9f\063" +
    "\uff9f\064\uff9f\066\uff9f\001\002\000\030\011\113\014\120" +
    "\035\116\036\114\037\106\040\103\042\100\045\102\050" +
    "\104\051\117\072\107\001\002\000\032\011\113\014\120" +
    "\035\116\036\114\037\106\040\103\042\100\045\102\050" +
    "\104\051\117\061\207\072\107\001\002\000\006\005\uffc2" +
    "\061\uffc2\001\002\000\014\075\213\076\212\077\214\100" +
    "\217\101\215\001\002\000\016\061\uffd4\075\uffd4\076\uffd4" +
    "\077\uffd4\100\uffd4\101\uffd4\001\002\000\004\065\237\001" +
    "\002\000\004\065\234\001\002\000\004\066\233\001\002" +
    "\000\004\065\230\001\002\000\016\061\226\075\213\076" +
    "\212\077\214\100\217\101\215\001\002\000\004\072\220" +
    "\001\002\000\004\065\221\001\002\000\004\072\222\001" +
    "\002\000\006\066\uffcd\072\uffcd\001\002\000\006\066\225" +
    "\072\224\001\002\000\006\066\uffce\072\uffce\001\002\000" +
    "\016\061\uffd0\075\uffd0\076\uffd0\077\uffd0\100\uffd0\101\uffd0" +
    "\001\002\000\006\005\uffd6\061\uffd6\001\002\000\016\061" +
    "\uffd5\075\uffd5\076\uffd5\077\uffd5\100\uffd5\101\uffd5\001\002" +
    "\000\004\072\231\001\002\000\004\066\232\001\002\000" +
    "\016\061\uffd1\075\uffd1\076\uffd1\077\uffd1\100\uffd1\101\uffd1" +
    "\001\002\000\016\061\uffcf\075\uffcf\076\uffcf\077\uffcf\100" +
    "\uffcf\101\uffcf\001\002\000\004\072\035\001\002\000\006" +
    "\064\037\066\236\001\002\000\016\061\uffd2\075\uffd2\076" +
    "\uffd2\077\uffd2\100\uffd2\101\uffd2\001\002\000\004\072\035" +
    "\001\002\000\006\064\037\066\241\001\002\000\016\061" +
    "\uffd3\075\uffd3\076\uffd3\077\uffd3\100\uffd3\101\uffd3\001\002" +
    "\000\010\016\251\020\243\022\250\001\002\000\004\060" +
    "\346\001\002\000\012\016\ufff6\020\ufff6\022\ufff6\061\ufff6" +
    "\001\002\000\012\016\ufff7\020\ufff7\022\ufff7\061\ufff7\001" +
    "\002\000\012\016\ufff4\020\ufff4\022\ufff4\061\ufff4\001\002" +
    "\000\012\016\ufff5\020\ufff5\022\ufff5\061\ufff5\001\002\000" +
    "\004\060\271\001\002\000\004\060\255\001\002\000\012" +
    "\016\251\020\243\022\250\061\253\001\002\000\006\005" +
    "\ufff9\061\ufff9\001\002\000\012\016\ufff8\020\ufff8\022\ufff8" +
    "\061\ufff8\001\002\000\004\017\260\001\002\000\006\017" +
    "\ufff1\061\ufff1\001\002\000\006\017\260\061\267\001\002" +
    "\000\004\072\261\001\002\000\004\054\262\001\002\000" +
    "\004\067\263\001\002\000\002\001\002\000\004\070\265" +
    "\001\002\000\004\066\266\001\002\000\006\017\ufff0\061" +
    "\ufff0\001\002\000\012\016\ufff3\020\ufff3\022\ufff3\061\ufff3" +
    "\001\002\000\006\017\ufff2\061\ufff2\001\002\000\012\023" +
    "\275\024\276\025\274\026\272\001\002\000\004\060\326" +
    "\001\002\000\014\023\uffe6\024\uffe6\025\uffe6\026\uffe6\061" +
    "\uffe6\001\002\000\004\065\313\001\002\000\004\065\305" +
    "\001\002\000\004\065\302\001\002\000\014\023\275\024" +
    "\276\025\274\026\272\061\300\001\002\000\012\016\uffe8" +
    "\020\uffe8\022\uffe8\061\uffe8\001\002\000\014\023\uffe7\024" +
    "\uffe7\025\uffe7\026\uffe7\061\uffe7\001\002\000\004\072\303" +
    "\001\002\000\004\066\304\001\002\000\014\023\uffe4\024" +
    "\uffe4\025\uffe4\026\uffe4\061\uffe4\001\002\000\004\072\306" +
    "\001\002\000\006\064\uffe1\066\uffe1\001\002\000\006\064" +
    "\310\066\311\001\002\000\004\072\312\001\002\000\014" +
    "\023\uffe5\024\uffe5\025\uffe5\026\uffe5\061\uffe5\001\002\000" +
    "\006\064\uffe0\066\uffe0\001\002\000\004\067\314\001\002" +
    "\000\004\072\315\001\002\000\004\054\324\001\002\000" +
    "\006\064\uffdf\070\uffdf\001\002\000\006\064\320\070\321" +
    "\001\002\000\004\072\315\001\002\000\004\066\322\001" +
    "\002\000\014\023\uffe3\024\uffe3\025\uffe3\026\uffe3\061\uffe3" +
    "\001\002\000\006\064\uffde\070\uffde\001\002\000\004\072" +
    "\325\001\002\000\006\064\uffdd\070\uffdd\001\002\000\004" +
    "\062\330\001\002\000\006\061\uffdb\062\uffdb\001\002\000" +
    "\004\072\334\001\002\000\006\061\332\062\330\001\002" +
    "\000\014\023\uffe2\024\uffe2\025\uffe2\026\uffe2\061\uffe2\001" +
    "\002\000\006\061\uffdc\062\uffdc\001\002\000\004\064\335" +
    "\001\002\000\010\027\340\072\337\073\341\001\002\000" +
    "\004\063\342\001\002\000\004\063\uffd9\001\002\000\004" +
    "\063\uffd7\001\002\000\004\063\uffd8\001\002\000\004\071" +
    "\343\001\002\000\004\072\344\001\002\000\004\066\345" +
    "\001\002\000\006\061\uffda\062\uffda\001\002\000\006\021" +
    "\352\041\350\001\002\000\006\041\350\061\364\001\002" +
    "\000\004\072\361\001\002\000\006\041\uffed\061\uffed\001" +
    "\002\000\004\054\354\001\002\000\006\041\uffec\061\uffec" +
    "\001\002\000\004\067\355\001\002\000\002\001\002\000" +
    "\004\070\357\001\002\000\004\066\360\001\002\000\006" +
    "\041\uffeb\061\uffeb\001\002\000\004\066\uffea\001\002\000" +
    "\004\066\363\001\002\000\006\041\uffe9\061\uffe9\001\002" +
    "\000\012\016\uffef\020\uffef\022\uffef\061\uffef\001\002\000" +
    "\006\041\uffee\061\uffee\001\002\000\004\102\370\001\002" +
    "\000\006\005\uffff\061\uffff\001\002\000\004\072\371\001" +
    "\002\000\004\066\372\001\002\000\004\002\000\001\002" +
    "\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\371\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\003\007\004\011" +
    "\005\015\026\012\032\013\045\014\001\001\000\014\004" +
    "\366\005\015\026\012\032\013\045\014\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\006\046\024\047\023\001\001\000\002\001\001\000\006" +
    "\047\042\051\043\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\031\035\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\052\045\001\001\000\002\001\001\000\002\001\001" +
    "\000\010\043\062\050\053\057\050\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\043\203\050\053\057\050" +
    "\001\001\000\010\043\202\050\053\057\050\001\001\000" +
    "\002\001\001\000\010\043\200\050\053\057\050\001\001" +
    "\000\010\043\177\050\053\057\050\001\001\000\002\001" +
    "\001\000\010\043\171\050\053\057\050\001\001\000\010" +
    "\043\170\050\053\057\050\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\010\043\065\050\053" +
    "\057\050\001\001\000\002\001\001\000\010\043\067\050" +
    "\053\057\050\001\001\000\002\001\001\000\012\043\071" +
    "\050\053\057\050\060\072\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\043\075\050\053\057\050\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\033\100\034" +
    "\104\035\107\036\120\037\111\040\110\041\114\001\001" +
    "\000\002\001\001\000\016\034\127\035\107\036\120\037" +
    "\111\040\110\041\114\001\001\000\010\043\163\050\053" +
    "\057\050\001\001\000\002\001\001\000\010\043\157\050" +
    "\053\057\050\001\001\000\002\001\001\000\010\043\156" +
    "\050\053\057\050\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\043\136\050" +
    "\053\057\050\001\001\000\010\043\135\050\053\057\050" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\012\042\124\043\123\050\053\057\050\001\001" +
    "\000\002\001\001\000\002\001\001\000\020\033\126\034" +
    "\104\035\107\036\120\037\111\040\110\041\114\001\001" +
    "\000\016\034\127\035\107\036\120\037\111\040\110\041" +
    "\114\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\043\134\050\053\057\050\001\001\000\010\043\133\050" +
    "\053\057\050\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\010\043\142\050\053\057\050\001\001" +
    "\000\002\001\001\000\012\042\144\043\123\050\053\057" +
    "\050\001\001\000\002\001\001\000\020\033\146\034\104" +
    "\035\107\036\120\037\111\040\110\041\114\001\001\000" +
    "\016\034\127\035\107\036\120\037\111\040\110\041\114" +
    "\001\001\000\020\033\151\034\104\035\107\036\120\037" +
    "\111\040\110\041\114\001\001\000\002\001\001\000\016" +
    "\034\127\035\107\036\120\037\111\040\110\041\114\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\043\155" +
    "\050\053\057\050\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\043\162" +
    "\050\053\057\050\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\043\167" +
    "\050\053\057\050\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\043\173\050\053\057\050" +
    "\001\001\000\002\001\001\000\010\043\175\050\053\057" +
    "\050\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\020\033\205\034\104\035\107" +
    "\036\120\037\111\040\110\041\114\001\001\000\016\034" +
    "\127\035\107\036\120\037\111\040\110\041\114\001\001" +
    "\000\002\001\001\000\006\027\215\030\210\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\030\226\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\044\222\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\031\234\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\031\237\001\001\000\002\001\001\000" +
    "\002\001\001\000\014\006\251\007\244\010\243\013\246" +
    "\017\245\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\012\007\253\010\243\013" +
    "\246\017\245\001\001\000\002\001\001\000\002\001\001" +
    "\000\006\011\256\012\255\001\001\000\002\001\001\000" +
    "\004\012\267\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\025\263\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\020\276\021\272\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\021\300\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\004\022\306\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\006\023" +
    "\316\024\315\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\024\322\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\006\054\330\055\326\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\055\332\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\004\056\335\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\010" +
    "\014\346\015\350\016\352\001\001\000\004\015\364\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\025\355\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\061\361\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintaxis$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintaxis$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintaxis$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public static TablaSimbolos tabla = new TablaSimbolos();

    private Symbol s;

    public Symbol getS(){
        return this.s;
    }

    public void syntax_error(Symbol s){
        this.s = s;
        System.err.println("Error sintáctico: "+ s.value);
    }   

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintaxis$actions {
  private final Sintaxis parser;

  /** Constructor */
  CUP$Sintaxis$actions(Sintaxis parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintaxis$do_action(
    int                        CUP$Sintaxis$act_num,
    java_cup.runtime.lr_parser CUP$Sintaxis$parser,
    java.util.Stack            CUP$Sintaxis$stack,
    int                        CUP$Sintaxis$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintaxis$result;

      /* select the action based on the action number */
      switch (CUP$Sintaxis$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 103: // argumentos ::= 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("argumentos",46, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 102: // argumentos ::= expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("argumentos",46, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // argumentos ::= argumentos COMA expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("argumentos",46, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // llamada_metodo ::= ID PAREN_ABRE argumentos PAREN_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("llamada_metodo",45, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // exp_llamada ::= ANALISIS_SINTACTICO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",38, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // exp_llamada ::= ANALISIS_LEXICO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",38, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // exp_llamada ::= GENERAR_TS PAREN_ABRE expresion COMA expresion PAREN_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",38, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // exp_llamada ::= COLUMNA expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",38, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // exp_llamada ::= LINEA expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",38, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // exp_llamada ::= VERIFICAR_ERRORES expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",38, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // exp_llamada ::= CARGAR_ARCHIVO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",38, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // expresion ::= PAREN_ABRE expresion PAREN_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // expresion ::= expresion OPE_ARITMETICO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // expresion ::= llamada_metodo 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // expresion ::= exp_llamada 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // expresion ::= CADENA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // expresion ::= NUMERO 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // expresion ::= ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // condicion ::= expresion OPE_LOGICO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion",32, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // condicion ::= expresion OPE_RELACIONAL expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion",32, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // condicion ::= expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion",32, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // ciclo_mientras ::= MIENTRAS PAREN_ABRE condicion PAREN_CIERRA instrucciones FIN_MIENTRAS 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("ciclo_mientras",30, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // condicion_si ::= SI PAREN_ABRE condicion PAREN_CIERRA instrucciones SINO instrucciones FIN_SI 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion_si",29, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-7)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // condicion_si ::= SI PAREN_ABRE condicion PAREN_CIERRA instrucciones FIN_SI 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion_si",29, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // llamada_reservada ::= CONSTRUIR_TABLA expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("llamada_reservada",31, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // funcion ::= LIMPIAR_ERRORES expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("funcion",28, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // funcion ::= VER_ERRORES expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("funcion",28, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // funcion ::= DIBUJAR expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("funcion",28, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // funcion ::= IMPRIMIR expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("funcion",28, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // asignacion ::= ARBOL ID OPE_ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("asignacion",27, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // asignacion ::= TOKENS ID OPE_ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("asignacion",27, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // asignacion ::= ENTRADA ID OPE_ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("asignacion",27, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // asignacion ::= ID OPE_ASIGNACION expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("asignacion",27, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // instruccion ::= ciclo_mientras 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",26, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // instruccion ::= condicion_si 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",26, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // instruccion ::= llamada_reservada PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",26, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // instruccion ::= funcion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",26, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // instruccion ::= asignacion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",26, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // instrucciones ::= instruccion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instrucciones",25, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // instrucciones ::= instrucciones instruccion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instrucciones",25, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // seccion_principal ::= SECCION PRINCIPAL LLAVE_ABRE instrucciones LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion_principal",24, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // instruccion_tabla ::= CONSTRUIR_TABLA expresion LLAVE_ABRE instrucciones LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion_tabla",40, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // instrucciones_tabla ::= 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instrucciones_tabla",39, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // instrucciones_tabla ::= instrucciones_tabla instruccion_tabla 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instrucciones_tabla",39, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // decl_tabla ::= TABLA ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_tabla",37, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // decl_tabla ::= ESTRUCTURA_TABLA ID LLAVE_ABRE CAMPO ids PUNTO_COMA LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_tabla",37, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-6)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // contenido_tabla ::= decl_tabla 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("contenido_tabla",36, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // contenido_tabla ::= contenido_tabla decl_tabla 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("contenido_tabla",36, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // seccion_tabla ::= SECCION TABLA_SIMBOLOS LLAVE_ABRE contenido_tabla instrucciones_tabla LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion_tabla",35, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // ids ::= ids COMA ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("ids",23, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // ids ::= ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("ids",23, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // producciones ::= ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("producciones",34, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // producciones ::= producciones ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("producciones",34, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // declaracion_sintac ::= VACIO PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // declaracion_sintac ::= REGLA ID DOS_PUNTOS producciones PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // declaracion_sintac ::= INICIO DOS_PUNTOS ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // declaracion_sintac ::= NO_TERMINALES DOS_PUNTOS ids PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // declaracion_sintac ::= TERMINALES DOS_PUNTOS ids PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // lista_declaracion_sintac ::= declaracion_sintac 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_declaracion_sintac",21, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // lista_declaracion_sintac ::= lista_declaracion_sintac declaracion_sintac 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_declaracion_sintac",21, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // seccion_sintactico ::= SECCION ANALISIS_SINTACTICO LLAVE_ABRE lista_declaracion_sintac LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion_sintactico",20, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // entrada_transicion ::= OTRO 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("entrada_transicion",44, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // entrada_transicion ::= CADENA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("entrada_transicion",44, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // entrada_transicion ::= ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("entrada_transicion",44, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // transicion ::= PAREN_ABRE ID COMA entrada_transicion PAREN_CIERRA OPE_TRANSICION ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("transicion",43, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-7)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // lista_transiciones ::= transicion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_transiciones",42, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // lista_transiciones ::= lista_transiciones transicion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_transiciones",42, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // estado_final ::= ID OPE_ASIGNACION ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("estado_final",18, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // lista_estados_finales ::= lista_estados_finales COMA estado_final 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_estados_finales",17, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // lista_estados_finales ::= estado_final 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_estados_finales",17, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // lista_estados ::= lista_estados COMA ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_estados",16, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // lista_estados ::= ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_estados",16, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // decl_automata ::= TRANSICIONES LLAVE_ABRE lista_transiciones LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_automata",15, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // decl_automata ::= ESTADOS_FINALES DOS_PUNTOS CORCHETE_ABRE lista_estados_finales CORCHETE_CIERRA PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_automata",15, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // decl_automata ::= ESTADO_INICIAL DOS_PUNTOS ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_automata",15, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // decl_automata ::= ESTADOS DOS_PUNTOS lista_estados PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_automata",15, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // lista_decl_automata ::= decl_automata 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_automata",14, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // lista_decl_automata ::= lista_decl_automata decl_automata 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_automata",14, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // def_automata ::= EJECUTAR_AUTOMATA LLAVE_ABRE lista_decl_automata LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("def_automata",13, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // decl_token ::= TOKEN ID NT$0 PUNTO_COMA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).value;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).value;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_token",11, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // NT$0 ::= 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.peek()).value;
 
    //registramos con LINEA (idleft) y COLUMNA (idright) y Sumamos 1 porque JCup empieza a contar en 0
    parser.tabla.registrarIdentificador((String)id, idleft + 1, idright + 1);
    //asignamos el tipo y la dirección
    parser.tabla.asignarTipoyDireccion((String)id, "TOKEN"); 
    System.out.println("Token registrado: " + id + " en linea: " + (idleft+1));

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("NT$0",47, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // decl_pal_res ::= PALABRAS_RESERVADAS OPE_ASIGNACION CORCHETE_ABRE lista_elementos CORCHETE_CIERRA PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_pal_res",12, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // lista_decl_tokens ::= decl_pal_res 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_tokens",10, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // lista_decl_tokens ::= decl_token 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_tokens",10, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // lista_decl_tokens ::= lista_decl_tokens decl_token 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_tokens",10, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // def_tokens ::= DEFINIR_TOKENS LLAVE_ABRE lista_decl_tokens LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("def_tokens",9, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // conjunto_decl ::= CONJUNTO ID OPE_ASIGNACION CORCHETE_ABRE lista_elementos CORCHETE_CIERRA PUNTO_COMA 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)).value;
		
    //Registrar con línea y columna
    parser.tabla.registrarIdentificador((String)id, idleft + 1, idright + 1);
    //Asignar tipo
    parser.tabla.asignarTipoyDireccion((String)id, "CONJUNTO_ALFABETO");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("conjunto_decl",8, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-6)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // lista_conjuntos ::= conjunto_decl 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_conjuntos",7, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // lista_conjuntos ::= lista_conjuntos conjunto_decl 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_conjuntos",7, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // def_alfabeto ::= DEFINIR_ALFABETO LLAVE_ABRE lista_conjuntos LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("def_alfabeto",6, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // declaracion_lex ::= def_automata 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_lex",5, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // declaracion_lex ::= def_tokens 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_lex",5, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // declaracion_lex ::= def_alfabeto 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_lex",5, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lista_declaracion_lex ::= declaracion_lex 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_declaracion_lex",4, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista_declaracion_lex ::= lista_declaracion_lex declaracion_lex 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_declaracion_lex",4, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // seccion_lexico ::= SECCION ANALISIS_LEXICO LLAVE_ABRE lista_declaracion_lex LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion_lexico",3, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // seccion ::= seccion_tabla 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion",2, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // seccion ::= seccion_principal 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion",2, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // seccion ::= seccion_sintactico 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion",2, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // seccion ::= seccion_lexico 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion",2, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_secciones ::= seccion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_secciones",1, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_secciones ::= lista_secciones seccion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_secciones",1, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= COMPILAR ID LLAVE_ABRE lista_secciones LLAVE_CIERRA EJECUTARPROG ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-7)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).value;
		RESULT = start_val;
              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintaxis$parser.done_parsing();
          return CUP$Sintaxis$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

