
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 14 00:00:49 MST 2025
//----------------------------------------------------

package codigo;

import java_cup.runtime.Symbol;

/** CUP v0.11a beta 20060608 generated parser.
  * @version Sun Dec 14 00:00:49 MST 2025
  */
public class Sintaxis extends java_cup.runtime.lr_parser {

  /** Default constructor. */
  public Sintaxis() {super();}

  /** Constructor which sets the default scanner. */
  public Sintaxis(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public Sintaxis(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\155\000\002\002\004\000\002\002\012\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\003\000\002\004\003\000\002\005\007\000" +
    "\002\006\004\000\002\006\003\000\002\007\003\000\002" +
    "\007\003\000\002\007\003\000\002\010\006\000\002\011" +
    "\004\000\002\011\003\000\002\012\011\000\002\025\003" +
    "\000\002\025\005\000\002\013\006\000\002\014\004\000" +
    "\002\014\003\000\002\014\003\000\002\016\010\000\002" +
    "\015\005\000\002\017\006\000\002\020\004\000\002\020" +
    "\003\000\002\021\006\000\002\021\006\000\002\021\010" +
    "\000\002\021\006\000\002\022\003\000\002\022\005\000" +
    "\002\023\003\000\002\023\005\000\002\024\005\000\002" +
    "\056\004\000\002\056\003\000\002\057\012\000\002\060" +
    "\003\000\002\060\003\000\002\060\003\000\002\026\007" +
    "\000\002\027\004\000\002\027\003\000\002\030\006\000" +
    "\002\030\006\000\002\030\006\000\002\030\007\000\002" +
    "\030\004\000\002\046\004\000\002\046\003\000\002\031" +
    "\003\000\002\031\005\000\002\032\003\000\002\032\005" +
    "\000\002\047\010\000\002\050\004\000\002\050\003\000" +
    "\002\051\011\000\002\051\005\000\002\033\003\000\002" +
    "\033\005\000\002\053\004\000\002\053\002\000\002\054" +
    "\007\000\002\034\007\000\002\035\004\000\002\035\003" +
    "\000\002\036\004\000\002\036\004\000\002\036\004\000" +
    "\002\036\003\000\002\036\003\000\002\037\005\000\002" +
    "\037\006\000\002\037\006\000\002\037\006\000\002\040" +
    "\004\000\002\040\004\000\002\040\004\000\002\040\004" +
    "\000\002\043\004\000\002\041\010\000\002\041\012\000" +
    "\002\042\010\000\002\044\003\000\002\044\005\000\002" +
    "\044\005\000\002\045\003\000\002\045\003\000\002\045" +
    "\003\000\002\045\003\000\002\045\003\000\002\045\005" +
    "\000\002\045\005\000\002\052\004\000\002\052\004\000" +
    "\002\052\004\000\002\052\004\000\002\052\010\000\002" +
    "\052\004\000\002\052\004\000\002\061\006\000\002\062" +
    "\005\000\002\062\003\000\002\062\002" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\u0101\000\004\004\005\001\002\000\004\002\u0103\001" +
    "\002\000\004\071\006\001\002\000\004\057\007\001\002" +
    "\000\004\005\011\001\002\000\006\005\011\060\376\001" +
    "\002\000\012\006\017\007\020\010\022\030\021\001\002" +
    "\000\006\005\ufffe\060\ufffe\001\002\000\006\005\ufffc\060" +
    "\ufffc\001\002\000\006\005\ufffb\060\ufffb\001\002\000\006" +
    "\005\ufffa\060\ufffa\001\002\000\006\005\ufffd\060\ufffd\001" +
    "\002\000\004\057\250\001\002\000\004\057\210\001\002" +
    "\000\004\057\157\001\002\000\004\057\023\001\002\000" +
    "\030\011\037\014\044\035\042\036\040\037\032\040\027" +
    "\041\024\044\026\047\030\050\043\071\033\001\002\000" +
    "\004\071\154\001\002\000\032\011\037\014\044\035\042" +
    "\036\040\037\032\040\027\041\024\044\026\047\030\050" +
    "\043\060\153\071\033\001\002\000\030\006\052\007\066" +
    "\034\057\045\056\046\054\051\061\052\060\061\055\071" +
    "\064\072\050\073\062\001\002\000\004\071\147\001\002" +
    "\000\030\006\052\007\066\034\057\045\056\046\054\051" +
    "\061\052\060\061\055\071\064\072\050\073\062\001\002" +
    "\000\040\011\uffbb\012\uffbb\013\uffbb\014\uffbb\015\uffbb\035" +
    "\uffbb\036\uffbb\037\uffbb\040\uffbb\041\uffbb\044\uffbb\047\uffbb" +
    "\050\uffbb\060\uffbb\071\uffbb\001\002\000\030\006\052\007" +
    "\066\034\057\045\056\046\054\051\061\052\060\061\055" +
    "\071\064\072\050\073\062\001\002\000\004\053\143\001" +
    "\002\000\004\065\142\001\002\000\040\011\uffb6\012\uffb6" +
    "\013\uffb6\014\uffb6\015\uffb6\035\uffb6\036\uffb6\037\uffb6\040" +
    "\uffb6\041\uffb6\044\uffb6\047\uffb6\050\uffb6\060\uffb6\071\uffb6" +
    "\001\002\000\040\011\uffb7\012\uffb7\013\uffb7\014\uffb7\015" +
    "\uffb7\035\uffb7\036\uffb7\037\uffb7\040\uffb7\041\uffb7\044\uffb7" +
    "\047\uffb7\050\uffb7\060\uffb7\071\uffb7\001\002\000\004\061" +
    "\132\001\002\000\004\071\127\001\002\000\004\065\126" +
    "\001\002\000\030\006\052\007\066\034\057\045\056\046" +
    "\054\051\061\052\060\061\055\071\064\072\050\073\062" +
    "\001\002\000\030\006\052\007\066\034\057\045\056\046" +
    "\054\051\061\052\060\061\055\071\064\072\050\073\062" +
    "\001\002\000\004\061\047\001\002\000\004\065\046\001" +
    "\002\000\040\011\uffb9\012\uffb9\013\uffb9\014\uffb9\015\uffb9" +
    "\035\uffb9\036\uffb9\037\uffb9\040\uffb9\041\uffb9\044\uffb9\047" +
    "\uffb9\050\uffb9\060\uffb9\071\uffb9\001\002\000\030\006\052" +
    "\007\066\034\057\045\056\046\054\051\061\052\060\061" +
    "\055\071\064\072\050\073\062\001\002\000\020\054\uffa4" +
    "\055\uffa4\056\uffa4\057\uffa4\062\uffa4\063\uffa4\065\uffa4\001" +
    "\002\000\020\054\uffa2\055\uffa2\056\uffa2\057\uffa2\062\uffa2" +
    "\063\uffa2\065\uffa2\001\002\000\030\006\052\007\066\034" +
    "\057\045\056\046\054\051\061\052\060\061\055\071\064" +
    "\072\050\073\062\001\002\000\020\054\uffa3\055\uffa3\056" +
    "\uffa3\057\uffa3\062\uffa3\063\uffa3\065\uffa3\001\002\000\030" +
    "\006\052\007\066\034\057\045\056\046\054\051\061\052" +
    "\060\061\055\071\064\072\050\073\062\001\002\000\030" +
    "\006\052\007\066\034\057\045\056\046\054\051\061\052" +
    "\060\061\055\071\064\072\050\073\062\001\002\000\030" +
    "\006\052\007\066\034\057\045\056\046\054\051\061\052" +
    "\060\061\055\071\064\072\050\073\062\001\002\000\004" +
    "\061\112\001\002\000\030\006\052\007\066\034\057\045" +
    "\056\046\054\051\061\052\060\061\055\071\064\072\050" +
    "\073\062\001\002\000\030\006\052\007\066\034\057\045" +
    "\056\046\054\051\061\052\060\061\055\071\064\072\050" +
    "\073\062\001\002\000\020\054\uffa5\055\uffa5\056\uffa5\057" +
    "\uffa5\062\uffa5\063\uffa5\065\uffa5\001\002\000\012\054\070" +
    "\055\105\056\104\062\uffa9\001\002\000\022\054\uffa6\055" +
    "\uffa6\056\uffa6\057\uffa6\061\076\062\uffa6\063\uffa6\065\uffa6" +
    "\001\002\000\004\062\072\001\002\000\030\006\052\007" +
    "\066\034\057\045\056\046\054\051\061\052\060\061\055" +
    "\071\064\072\050\073\062\001\002\000\020\054\070\055" +
    "\uff99\056\uff99\057\uff99\062\uff99\063\uff99\065\uff99\001\002" +
    "\000\030\006\052\007\066\034\057\045\056\046\054\051" +
    "\061\052\060\061\055\071\064\072\050\073\062\001\002" +
    "\000\020\054\uffa1\055\uffa1\056\uffa1\057\uffa1\062\uffa1\063" +
    "\uffa1\065\uffa1\001\002\000\030\011\037\014\044\035\042" +
    "\036\040\037\032\040\027\041\024\044\026\047\030\050" +
    "\043\071\033\001\002\000\032\011\037\014\044\015\075" +
    "\035\042\036\040\037\032\040\027\041\024\044\026\047" +
    "\030\050\043\071\033\001\002\000\040\011\uffbc\012\uffbc" +
    "\013\uffbc\014\uffbc\015\uffbc\035\uffbc\036\uffbc\037\uffbc\040" +
    "\uffbc\041\uffbc\044\uffbc\047\uffbc\050\uffbc\060\uffbc\071\uffbc" +
    "\001\002\000\040\011\uffaa\012\uffaa\013\uffaa\014\uffaa\015" +
    "\uffaa\035\uffaa\036\uffaa\037\uffaa\040\uffaa\041\uffaa\044\uffaa" +
    "\047\uffaa\050\uffaa\060\uffaa\071\uffaa\001\002\000\034\006" +
    "\052\007\066\034\057\045\056\046\054\051\061\052\060" +
    "\061\055\062\uff95\063\uff95\071\064\072\050\073\062\001" +
    "\002\000\010\054\070\062\uff96\063\uff96\001\002\000\006" +
    "\062\102\063\101\001\002\000\030\006\052\007\066\034" +
    "\057\045\056\046\054\051\061\052\060\061\055\071\064" +
    "\072\050\073\062\001\002\000\020\054\uff98\055\uff98\056" +
    "\uff98\057\uff98\062\uff98\063\uff98\065\uff98\001\002\000\010" +
    "\054\070\062\uff97\063\uff97\001\002\000\030\006\052\007" +
    "\066\034\057\045\056\046\054\051\061\052\060\061\055" +
    "\071\064\072\050\073\062\001\002\000\030\006\052\007" +
    "\066\034\057\045\056\046\054\051\061\052\060\061\055" +
    "\071\064\072\050\073\062\001\002\000\006\054\070\062" +
    "\uffa8\001\002\000\006\054\070\062\uffa7\001\002\000\020" +
    "\054\070\055\uff9d\056\uff9d\057\uff9d\062\uff9d\063\uff9d\065" +
    "\uff9d\001\002\000\020\054\070\055\uff9c\056\uff9c\057\uff9c" +
    "\062\uff9c\063\uff9c\065\uff9c\001\002\000\030\006\052\007" +
    "\066\034\057\045\056\046\054\051\061\052\060\061\055" +
    "\071\064\072\050\073\062\001\002\000\006\054\070\063" +
    "\114\001\002\000\030\006\052\007\066\034\057\045\056" +
    "\046\054\051\061\052\060\061\055\071\064\072\050\073" +
    "\062\001\002\000\006\054\070\062\116\001\002\000\020" +
    "\054\uff9b\055\uff9b\056\uff9b\057\uff9b\062\uff9b\063\uff9b\065" +
    "\uff9b\001\002\000\020\054\070\055\uff9f\056\uff9f\057\uff9f" +
    "\062\uff9f\063\uff9f\065\uff9f\001\002\000\006\054\070\062" +
    "\121\001\002\000\020\054\uffa0\055\uffa0\056\uffa0\057\uffa0" +
    "\062\uffa0\063\uffa0\065\uffa0\001\002\000\020\054\070\055" +
    "\uff9e\056\uff9e\057\uff9e\062\uff9e\063\uff9e\065\uff9e\001\002" +
    "\000\020\054\070\055\uff9a\056\uff9a\057\uff9a\062\uff9a\063" +
    "\uff9a\065\uff9a\001\002\000\006\054\070\065\uffae\001\002" +
    "\000\006\054\070\065\uffad\001\002\000\040\011\uffb8\012" +
    "\uffb8\013\uffb8\014\uffb8\015\uffb8\035\uffb8\036\uffb8\037\uffb8" +
    "\040\uffb8\041\uffb8\044\uffb8\047\uffb8\050\uffb8\060\uffb8\071" +
    "\uffb8\001\002\000\004\053\130\001\002\000\030\006\052" +
    "\007\066\034\057\045\056\046\054\051\061\052\060\061" +
    "\055\071\064\072\050\073\062\001\002\000\006\054\070" +
    "\065\uffb4\001\002\000\030\006\052\007\066\034\057\045" +
    "\056\046\054\051\061\052\060\061\055\071\064\072\050" +
    "\073\062\001\002\000\004\062\134\001\002\000\030\011" +
    "\037\014\044\035\042\036\040\037\032\040\027\041\024" +
    "\044\026\047\030\050\043\071\033\001\002\000\034\011" +
    "\037\012\136\013\137\014\044\035\042\036\040\037\032" +
    "\040\027\041\024\044\026\047\030\050\043\071\033\001" +
    "\002\000\030\011\037\014\044\035\042\036\040\037\032" +
    "\040\027\041\024\044\026\047\030\050\043\071\033\001" +
    "\002\000\040\011\uffac\012\uffac\013\uffac\014\uffac\015\uffac" +
    "\035\uffac\036\uffac\037\uffac\040\uffac\041\uffac\044\uffac\047" +
    "\uffac\050\uffac\060\uffac\071\uffac\001\002\000\032\011\037" +
    "\013\141\014\044\035\042\036\040\037\032\040\027\041" +
    "\024\044\026\047\030\050\043\071\033\001\002\000\040" +
    "\011\uffab\012\uffab\013\uffab\014\uffab\015\uffab\035\uffab\036" +
    "\uffab\037\uffab\040\uffab\041\uffab\044\uffab\047\uffab\050\uffab" +
    "\060\uffab\071\uffab\001\002\000\040\011\uffba\012\uffba\013" +
    "\uffba\014\uffba\015\uffba\035\uffba\036\uffba\037\uffba\040\uffba" +
    "\041\uffba\044\uffba\047\uffba\050\uffba\060\uffba\071\uffba\001" +
    "\002\000\030\006\052\007\066\034\057\045\056\046\054" +
    "\051\061\052\060\061\055\071\064\072\050\073\062\001" +
    "\002\000\006\054\070\065\uffb5\001\002\000\006\054\070" +
    "\065\uffb1\001\002\000\006\054\070\065\uffaf\001\002\000" +
    "\004\053\150\001\002\000\030\006\052\007\066\034\057" +
    "\045\056\046\054\051\061\052\060\061\055\071\064\072" +
    "\050\073\062\001\002\000\006\054\070\065\uffb2\001\002" +
    "\000\006\054\070\065\uffb0\001\002\000\006\005\uffbd\060" +
    "\uffbd\001\002\000\004\053\155\001\002\000\030\006\052" +
    "\007\066\034\057\045\056\046\054\051\061\052\060\061" +
    "\055\071\064\072\050\073\062\001\002\000\006\054\070" +
    "\065\uffb3\001\002\000\006\031\162\033\163\001\002\000" +
    "\012\031\uffc5\033\uffc5\035\uffc5\060\uffc5\001\002\000\012" +
    "\031\162\033\163\035\uffbf\060\uffbf\001\002\000\004\071" +
    "\166\001\002\000\004\071\164\001\002\000\004\065\165" +
    "\001\002\000\012\031\uffc3\033\uffc3\035\uffc3\060\uffc3\001" +
    "\002\000\004\057\167\001\002\000\004\032\170\001\002" +
    "\000\004\071\171\001\002\000\006\063\uffc2\065\uffc2\001" +
    "\002\000\006\063\173\065\174\001\002\000\004\071\176" +
    "\001\002\000\004\060\175\001\002\000\012\031\uffc4\033" +
    "\uffc4\035\uffc4\060\uffc4\001\002\000\006\063\uffc1\065\uffc1" +
    "\001\002\000\012\031\uffc6\033\uffc6\035\uffc6\060\uffc6\001" +
    "\002\000\006\035\203\060\201\001\002\000\006\005\uffc7" +
    "\060\uffc7\001\002\000\006\035\uffc0\060\uffc0\001\002\000" +
    "\030\006\052\007\066\034\057\045\056\046\054\051\061" +
    "\052\060\061\055\071\064\072\050\073\062\001\002\000" +
    "\006\054\070\057\205\001\002\000\030\011\037\014\044" +
    "\035\042\036\040\037\032\040\027\041\024\044\026\047" +
    "\030\050\043\071\033\001\002\000\032\011\037\014\044" +
    "\035\042\036\040\037\032\040\027\041\024\044\026\047" +
    "\030\050\043\060\207\071\033\001\002\000\006\035\uffbe" +
    "\060\uffbe\001\002\000\014\043\212\074\213\075\215\076" +
    "\217\077\216\001\002\000\016\043\uffd3\060\uffd3\074\uffd3" +
    "\075\uffd3\076\uffd3\077\uffd3\001\002\000\004\064\242\001" +
    "\002\000\004\064\234\001\002\000\016\043\212\060\232" +
    "\074\213\075\215\076\217\077\216\001\002\000\004\065" +
    "\231\001\002\000\004\064\226\001\002\000\004\071\220" +
    "\001\002\000\004\064\221\001\002\000\004\071\222\001" +
    "\002\000\006\065\uffcc\071\uffcc\001\002\000\006\065\225" +
    "\071\224\001\002\000\006\065\uffcd\071\uffcd\001\002\000" +
    "\016\043\uffcf\060\uffcf\074\uffcf\075\uffcf\076\uffcf\077\uffcf" +
    "\001\002\000\004\071\227\001\002\000\004\065\230\001" +
    "\002\000\016\043\uffd0\060\uffd0\074\uffd0\075\uffd0\076\uffd0" +
    "\077\uffd0\001\002\000\016\043\uffce\060\uffce\074\uffce\075" +
    "\uffce\076\uffce\077\uffce\001\002\000\006\005\uffd5\060\uffd5" +
    "\001\002\000\016\043\uffd4\060\uffd4\074\uffd4\075\uffd4\076" +
    "\uffd4\077\uffd4\001\002\000\004\071\235\001\002\000\006" +
    "\063\uffc9\065\uffc9\001\002\000\006\063\237\065\240\001" +
    "\002\000\004\071\241\001\002\000\016\043\uffd1\060\uffd1" +
    "\074\uffd1\075\uffd1\076\uffd1\077\uffd1\001\002\000\006\063" +
    "\uffc8\065\uffc8\001\002\000\004\071\243\001\002\000\006" +
    "\063\uffcb\065\uffcb\001\002\000\006\063\245\065\246\001" +
    "\002\000\004\071\247\001\002\000\016\043\uffd2\060\uffd2" +
    "\074\uffd2\075\uffd2\076\uffd2\077\uffd2\001\002\000\006\063" +
    "\uffca\065\uffca\001\002\000\010\016\257\020\251\022\256" +
    "\001\002\000\004\057\357\001\002\000\012\016\ufff6\020" +
    "\ufff6\022\ufff6\060\ufff6\001\002\000\012\016\ufff7\020\ufff7" +
    "\022\ufff7\060\ufff7\001\002\000\012\016\ufff4\020\ufff4\022" +
    "\ufff4\060\ufff4\001\002\000\012\016\ufff5\020\ufff5\022\ufff5" +
    "\060\ufff5\001\002\000\004\057\302\001\002\000\004\057" +
    "\263\001\002\000\012\016\257\020\251\022\256\060\261" +
    "\001\002\000\006\005\ufff9\060\ufff9\001\002\000\012\016" +
    "\ufff8\020\ufff8\022\ufff8\060\ufff8\001\002\000\004\017\266" +
    "\001\002\000\006\017\ufff1\060\ufff1\001\002\000\006\017" +
    "\266\060\300\001\002\000\004\071\267\001\002\000\004" +
    "\053\270\001\002\000\004\066\271\001\002\000\004\072" +
    "\273\001\002\000\006\063\274\067\275\001\002\000\006" +
    "\063\uffef\067\uffef\001\002\000\004\072\277\001\002\000" +
    "\004\065\276\001\002\000\006\017\ufff0\060\ufff0\001\002" +
    "\000\006\063\uffee\067\uffee\001\002\000\012\016\ufff3\020" +
    "\ufff3\022\ufff3\060\ufff3\001\002\000\006\017\ufff2\060\ufff2" +
    "\001\002\000\012\023\306\024\307\025\305\026\303\001" +
    "\002\000\004\057\337\001\002\000\014\023\uffe5\024\uffe5" +
    "\025\uffe5\026\uffe5\060\uffe5\001\002\000\004\064\324\001" +
    "\002\000\004\064\316\001\002\000\004\064\313\001\002" +
    "\000\014\023\306\024\307\025\305\026\303\060\311\001" +
    "\002\000\012\016\uffe7\020\uffe7\022\uffe7\060\uffe7\001\002" +
    "\000\014\023\uffe6\024\uffe6\025\uffe6\026\uffe6\060\uffe6\001" +
    "\002\000\004\071\314\001\002\000\004\065\315\001\002" +
    "\000\014\023\uffe3\024\uffe3\025\uffe3\026\uffe3\060\uffe3\001" +
    "\002\000\004\071\317\001\002\000\006\063\uffe0\065\uffe0" +
    "\001\002\000\006\063\321\065\322\001\002\000\004\071" +
    "\323\001\002\000\014\023\uffe4\024\uffe4\025\uffe4\026\uffe4" +
    "\060\uffe4\001\002\000\006\063\uffdf\065\uffdf\001\002\000" +
    "\004\066\325\001\002\000\004\071\326\001\002\000\004" +
    "\053\335\001\002\000\006\063\uffde\067\uffde\001\002\000" +
    "\006\063\331\067\332\001\002\000\004\071\326\001\002" +
    "\000\004\065\333\001\002\000\014\023\uffe2\024\uffe2\025" +
    "\uffe2\026\uffe2\060\uffe2\001\002\000\006\063\uffdd\067\uffdd" +
    "\001\002\000\004\071\336\001\002\000\006\063\uffdc\067" +
    "\uffdc\001\002\000\004\061\341\001\002\000\006\060\uffda" +
    "\061\uffda\001\002\000\004\071\345\001\002\000\006\060" +
    "\343\061\341\001\002\000\014\023\uffe1\024\uffe1\025\uffe1" +
    "\026\uffe1\060\uffe1\001\002\000\006\060\uffdb\061\uffdb\001" +
    "\002\000\004\063\346\001\002\000\010\027\351\071\350" +
    "\072\352\001\002\000\004\062\353\001\002\000\004\062" +
    "\uffd8\001\002\000\004\062\uffd6\001\002\000\004\062\uffd7" +
    "\001\002\000\004\070\354\001\002\000\004\071\355\001" +
    "\002\000\004\065\356\001\002\000\006\060\uffd9\061\uffd9" +
    "\001\002\000\006\021\363\042\361\001\002\000\006\042" +
    "\361\060\374\001\002\000\004\071\372\001\002\000\006" +
    "\042\uffeb\060\uffeb\001\002\000\004\053\365\001\002\000" +
    "\006\042\uffea\060\uffea\001\002\000\004\066\366\001\002" +
    "\000\004\072\273\001\002\000\006\063\274\067\370\001" +
    "\002\000\004\065\371\001\002\000\006\042\uffe9\060\uffe9" +
    "\001\002\000\004\065\373\001\002\000\006\042\uffe8\060" +
    "\uffe8\001\002\000\012\016\uffed\020\uffed\022\uffed\060\uffed" +
    "\001\002\000\006\042\uffec\060\uffec\001\002\000\004\100" +
    "\u0100\001\002\000\006\005\uffff\060\uffff\001\002\000\004" +
    "\071\u0101\001\002\000\004\065\u0102\001\002\000\004\002" +
    "\000\001\002\000\004\002\001\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\u0101\000\004\002\003\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\016\003\007\004\011" +
    "\005\015\026\012\034\013\047\014\001\001\000\014\004" +
    "\376\005\015\026\012\034\013\047\014\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\020\035\024\036\030\037\033\040\044\041\035\042\034" +
    "\043\040\001\001\000\002\001\001\000\016\036\073\037" +
    "\033\040\044\041\035\042\034\043\040\001\001\000\010" +
    "\045\151\052\052\061\050\001\001\000\002\001\001\000" +
    "\010\045\145\052\052\061\050\001\001\000\002\001\001" +
    "\000\010\045\144\052\052\061\050\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\045\124\052\052\061\050\001\001\000\010\045\123" +
    "\052\052\061\050\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\012\044\064\045\062\052\052" +
    "\061\050\001\001\000\002\001\001\000\002\001\001\000" +
    "\010\045\122\052\052\061\050\001\001\000\002\001\001" +
    "\000\010\045\121\052\052\061\050\001\001\000\010\045" +
    "\117\052\052\061\050\001\001\000\010\045\116\052\052" +
    "\061\050\001\001\000\002\001\001\000\010\045\110\052" +
    "\052\061\050\001\001\000\010\045\107\052\052\061\050" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\045\066\052\052\061\050" +
    "\001\001\000\002\001\001\000\010\045\070\052\052\061" +
    "\050\001\001\000\002\001\001\000\020\035\072\036\030" +
    "\037\033\040\044\041\035\042\034\043\040\001\001\000" +
    "\016\036\073\037\033\040\044\041\035\042\034\043\040" +
    "\001\001\000\002\001\001\000\002\001\001\000\012\045" +
    "\076\052\052\061\050\062\077\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\045\102\052\052\061\050\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\045\106" +
    "\052\052\061\050\001\001\000\010\045\105\052\052\061" +
    "\050\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\010\045\112\052\052\061" +
    "\050\001\001\000\002\001\001\000\010\045\114\052\052" +
    "\061\050\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\010\045\130" +
    "\052\052\061\050\001\001\000\002\001\001\000\012\044" +
    "\132\045\062\052\052\061\050\001\001\000\002\001\001" +
    "\000\020\035\134\036\030\037\033\040\044\041\035\042" +
    "\034\043\040\001\001\000\016\036\073\037\033\040\044" +
    "\041\035\042\034\043\040\001\001\000\020\035\137\036" +
    "\030\037\033\040\044\041\035\042\034\043\040\001\001" +
    "\000\002\001\001\000\016\036\073\037\033\040\044\041" +
    "\035\042\034\043\040\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\045\143\052\052\061\050\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\045\150\052\052\061\050\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\010\045\155\052\052\061\050\001\001\000" +
    "\002\001\001\000\006\050\160\051\157\001\001\000\002" +
    "\001\001\000\006\051\176\053\177\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\004\033\171\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\054\201\001\001\000\002\001\001" +
    "\000\002\001\001\000\010\045\203\052\052\061\050\001" +
    "\001\000\002\001\001\000\020\035\205\036\030\037\033" +
    "\040\044\041\035\042\034\043\040\001\001\000\016\036" +
    "\073\037\033\040\044\041\035\042\034\043\040\001\001" +
    "\000\002\001\001\000\006\027\213\030\210\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\030\232\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\046\222\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\032\235\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\031\243\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\014\006\257\007\252\010\251\013\254\017\253" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\012\007\261\010\251\013\254\017" +
    "\253\001\001\000\002\001\001\000\002\001\001\000\006" +
    "\011\264\012\263\001\001\000\002\001\001\000\004\012" +
    "\300\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\025\271\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\020\307\021\303\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\021\311\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\022\317\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\006\023\327\024\326" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\024\333\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\006\056\341\057\337\001\001\000\002\001\001" +
    "\000\002\001\001\000\004\057\343\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\060\346" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\010\014\357\015" +
    "\361\016\363\001\001\000\004\015\374\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\025\366\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$Sintaxis$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$Sintaxis$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$Sintaxis$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public static TablaSimbolos tabla;
    private Symbol s;
    private java.util.List<String> errores = new java.util.ArrayList<>();
    private java_cup.runtime.Scanner scanner;
    private javax.swing.JTextPane jErrorArea;

    // ---- CONSTRUCTOR QUE SI SE USA ----
    public Sintaxis(java_cup.runtime.Scanner s, javax.swing.JTextPane area, TablaSimbolos t){
        super(s);           // llama al parser de CUP
        this.scanner = s;   // guarda el scanner
        this.jErrorArea = area;   // guarda tu JTextPane
        Sintaxis.tabla = t; //tabla compartida entre el lexico y sintactico

    }

    public Symbol getS(){ 
        return this.s; 
    }
    
    public java.util.List<String> getErrores(){ 
        return this.errores; 
    }
    
    private void escribirJErrorArea(final String mensaje) {
        if (jErrorArea == null) return;
        javax.swing.SwingUtilities.invokeLater(() -> {
            try {
                javax.swing.text.StyledDocument doc = jErrorArea.getStyledDocument();
                doc.insertString(doc.getLength(), mensaje + "\n", null);
                jErrorArea.setCaretPosition(doc.getLength());
            } catch (Exception ex) {
                System.err.println("Error al escribir en jErrorArea: " + ex);
            }
            });

    }
    
    private void registrarError(String mensaje) {
        errores.add(mensaje);
        System.err.println(mensaje);   // Rojo en consola de NetBeans
        escribirJErrorArea(mensaje); // Texto en tu JTextPane
    }


    private String obtenerSugerencia(Symbol token) {
        if (token == null) return "Archivo incompleto.";
        
        switch (token.sym) {
            case sym.PUNTO_COMA:   
                return "Falta una instruccion antes del ';' o hay un ';' de más.";
            case sym.COMA:   
                return "Coma mal colocada o falta otro elemento en la lista.";
            case sym.DOS_PUNTOS:   
                return "Falta una lista despues de ':' por ejemplo (terminales: A,B,C).";    
            case sym.OPE_ASIGNACION:   
                return "Asignación incompleta: falta una expresion a la derecha o un identificador a la izquierda."; 
            case sym.PAREN_ABRE:   
                return "Falta expresión o condición despues de '('";
            case sym.PAREN_CIERRA: 
                return "Parentesis de cierre sin apertura o falta algo antes de ')'";
            case sym.LLAVE_ABRE: 
                return "Llave '{' inesperada, revisa si falta una palabra reservada o cabecera antes del bloque"; 
            case sym.LLAVE_CIERRA: 
                return "Llave '}' inesperada, Posible bloque vacío o falta cerrar una instrucción anterior.";

            case sym.ID:           
                return "Identificador inesperado, falta un operador o palabra reservada antes.";
            case sym.NUMERO:       
                return "Número inesperado, revisa la expresión o asignación.";
            case sym.CADENA:
                return "Cadena inesperada, revisa si el token/lugar acepta la cadena.";

            case sym.SI:
                return "Estructura 'si' mal formada, revisa condición y bloque.";
            case sym.SINO:         
                return "El 'sino' debe ir despues de un 'si'.";
            case sym.FIN_SI:       
                return "Cierre 'fin_si' sin un 'si' previo";
            case sym.MIENTRAS:
                return "Estructura 'mientras' mal formada, revisa condición y bloque.";
            case sym.FIN_MIENTRAS:
                return "Cierre 'fin_mientras' sin un 'mientras' previo.";

            case sym.COMPILAR:
                return "Error en la cabecera 'compilar': revisa nombre y llaves.";
            case sym.SECCION:
                return "Sección mal declarada: revisa 'seccion <nombre> { ... }'.";
            case sym.ANALISIS_LEXICO:
                return "Error dentro de la sección 'analisis_lexico'.";
            case sym.ANALISIS_SINTACTICO:
                return "Error dentro de la sección 'analisis_sintactico'.";
            case sym.PRINCIPAL:
                return "Error dentro de la sección 'principal'.";

            case sym.EOF:          
                return "El archivo terminó antes de cerrar una estructura, falta un '}' o una sección.";
            default:               
                return "Revisa la estructura anterior a esta instruccion.";
        }
    }
    
    public void syntax_error(Symbol tokenActual){
        this.s = tokenActual;

        String valorToken = (tokenActual == null || tokenActual.value == null) ? "<EOF>" : cur_token.value.toString();
        int linea = (tokenActual == null) ? -1 : (tokenActual.left + 1);
        int columna  = (tokenActual == null) ? -1 : (tokenActual.right +1);
        
        // Obtener que se esperaba
        String sugerencia = obtenerSugerencia(tokenActual);

        String errorMsj = String.format("Error Sintáctico en la Línea %d, Columna %d: Se encontró \"%s\". Sugerencia: [%s].", 
                                        linea, columna, valorToken, sugerencia);
      
        // Registramos el error
        registrarError(errorMsj);      
        
        //Recuperacion de errores (MODO PANICO)
        try {
            if (tokenActual == null || tokenActual.sym == sym.EOF) return;
            java_cup.runtime.Symbol t;

            while(true) {
                t = scanner.next_token();
                if (t == null || t.sym == sym.EOF) break;
                
                if(t.sym == sym.PUNTO_COMA || t.sym == sym.LLAVE_CIERRA) {
                    break;
                }
            }

        } catch (Exception e){
             registrarError("Error durante recuperación de errores sintácticos: " + e.getMessage());
        }
    }

}

/** Cup generated class to encapsulate user supplied action code.*/
class CUP$Sintaxis$actions {
  private final Sintaxis parser;

  /** Constructor */
  CUP$Sintaxis$actions(Sintaxis parser) {
    this.parser = parser;
  }

  /** Method with the actual generated action code. */
  public final java_cup.runtime.Symbol CUP$Sintaxis$do_action(
    int                        CUP$Sintaxis$act_num,
    java_cup.runtime.lr_parser CUP$Sintaxis$parser,
    java.util.Stack            CUP$Sintaxis$stack,
    int                        CUP$Sintaxis$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$Sintaxis$result;

      /* select the action based on the action number */
      switch (CUP$Sintaxis$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 108: // argumentos ::= 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("argumentos",48, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 107: // argumentos ::= expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("argumentos",48, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 106: // argumentos ::= argumentos COMA expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("argumentos",48, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 105: // llamada_metodo ::= ID PAREN_ABRE argumentos PAREN_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("llamada_metodo",47, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 104: // exp_llamada ::= ANALISIS_SINTACTICO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",40, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 103: // exp_llamada ::= ANALISIS_LEXICO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",40, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 102: // exp_llamada ::= GENERAR_TS PAREN_ABRE expresion COMA expresion PAREN_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",40, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 101: // exp_llamada ::= COLUMNA expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",40, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 100: // exp_llamada ::= LINEA expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",40, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 99: // exp_llamada ::= VERIFICAR_ERRORES expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",40, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 98: // exp_llamada ::= CARGAR_ARCHIVO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("exp_llamada",40, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 97: // expresion ::= PAREN_ABRE expresion PAREN_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",35, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 96: // expresion ::= expresion OPE_ARITMETICO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",35, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 95: // expresion ::= llamada_metodo 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",35, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 94: // expresion ::= exp_llamada 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",35, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 93: // expresion ::= CADENA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",35, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 92: // expresion ::= NUMERO 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",35, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 91: // expresion ::= ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("expresion",35, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 90: // condicion ::= expresion OPE_LOGICO expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion",34, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 89: // condicion ::= expresion OPE_RELACIONAL expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion",34, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 88: // condicion ::= expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion",34, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 87: // ciclo_mientras ::= MIENTRAS PAREN_ABRE condicion PAREN_CIERRA instrucciones FIN_MIENTRAS 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("ciclo_mientras",32, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 86: // condicion_si ::= SI PAREN_ABRE condicion PAREN_CIERRA instrucciones SINO instrucciones FIN_SI 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion_si",31, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-7)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 85: // condicion_si ::= SI PAREN_ABRE condicion PAREN_CIERRA instrucciones FIN_SI 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("condicion_si",31, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 84: // llamada_reservada ::= CONSTRUIR_TABLA expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("llamada_reservada",33, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 83: // funcion ::= LIMPIAR_ERRORES expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("funcion",30, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 82: // funcion ::= VER_ERRORES expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("funcion",30, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 81: // funcion ::= DIBUJAR expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("funcion",30, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 80: // funcion ::= IMPRIMIR expresion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("funcion",30, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 79: // asignacion ::= ARBOL ID OPE_ASIGNACION expresion 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).value;
		
   parser.tabla.registrarIdentificador((String)id, idleft+1, idright+1);
   parser.tabla.asignarTipoyDireccion((String)id, "ARBOL");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("asignacion",29, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 78: // asignacion ::= TOKENS ID OPE_ASIGNACION expresion 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).value;
		
   parser.tabla.registrarIdentificador((String)id, idleft+1, idright+1);
   parser.tabla.asignarTipoyDireccion((String)id, "VARIABLE_TOKENS");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("asignacion",29, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 77: // asignacion ::= ENTRADA ID OPE_ASIGNACION expresion 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).value;
		
   parser.tabla.registrarIdentificador((String)id, idleft+1, idright+1);
   parser.tabla.asignarTipoyDireccion((String)id, "ENTRADA");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("asignacion",29, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 76: // asignacion ::= ID OPE_ASIGNACION expresion 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)).value;
		
   parser.tabla.registrarIdentificador((String)id, idleft+1, idright+1);
   parser.tabla.asignarTipoyDireccion((String)id, "VARIABLE");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("asignacion",29, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 75: // instruccion ::= ciclo_mientras 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",28, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 74: // instruccion ::= condicion_si 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",28, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 73: // instruccion ::= llamada_reservada PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",28, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 72: // instruccion ::= funcion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",28, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 71: // instruccion ::= asignacion PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion",28, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 70: // instrucciones ::= instruccion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instrucciones",27, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 69: // instrucciones ::= instrucciones instruccion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instrucciones",27, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 68: // seccion_principal ::= SECCION PRINCIPAL LLAVE_ABRE instrucciones LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion_principal",26, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 67: // instruccion_tabla ::= CONSTRUIR_TABLA expresion LLAVE_ABRE instrucciones LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instruccion_tabla",42, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 66: // instrucciones_tabla ::= 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instrucciones_tabla",41, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 65: // instrucciones_tabla ::= instrucciones_tabla instruccion_tabla 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("instrucciones_tabla",41, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 64: // ids_campo ::= ids_campo COMA ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.peek()).value;
		
  Sintaxis.tabla.registrarIdentificador((String)id,idleft+1,idright+1);
  Sintaxis.tabla.asignarTipoyDireccion((String)id,"CAMPO");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("ids_campo",25, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 63: // ids_campo ::= ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.peek()).value;
		
  Sintaxis.tabla.registrarIdentificador((String)id,idleft+1,idright+1);
  Sintaxis.tabla.asignarTipoyDireccion((String)id,"CAMPO");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("ids_campo",25, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 62: // decl_tabla ::= TABLA ID PUNTO_COMA 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).value;
		
   parser.tabla.registrarIdentificador((String)id, idleft+1, idright+1);
   parser.tabla.asignarTipoyDireccion((String)id, "TABLA");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_tabla",39, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 61: // decl_tabla ::= ESTRUCTURA_TABLA ID LLAVE_ABRE CAMPO ids_campo PUNTO_COMA LLAVE_CIERRA 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)).value;
		
    parser.tabla.registrarIdentificador((String)id, idleft+1, idright+1);
    parser.tabla.asignarTipoyDireccion((String)id, "ESTRUCTURA_TABLA");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_tabla",39, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-6)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 60: // contenido_tabla ::= decl_tabla 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("contenido_tabla",38, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 59: // contenido_tabla ::= contenido_tabla decl_tabla 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("contenido_tabla",38, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 58: // seccion_tabla ::= SECCION TABLA_SIMBOLOS LLAVE_ABRE contenido_tabla instrucciones_tabla LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion_tabla",37, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 57: // ids_noterminales ::= ids_noterminales COMA ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.peek()).value;
		
  Sintaxis.tabla.registrarIdentificador((String)id,idleft+1,idright+1);
  Sintaxis.tabla.asignarTipoyDireccion((String)id,"NO_TERMINAL");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("ids_noterminales",24, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 56: // ids_noterminales ::= ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.peek()).value;
		
  Sintaxis.tabla.registrarIdentificador((String)id,idleft+1,idright+1);
  Sintaxis.tabla.asignarTipoyDireccion((String)id,"NO_TERMINAL");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("ids_noterminales",24, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 55: // ids_terminales ::= ids_terminales COMA ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("ids_terminales",23, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 54: // ids_terminales ::= ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("ids_terminales",23, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 53: // producciones ::= ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("producciones",36, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 52: // producciones ::= producciones ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("producciones",36, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 51: // declaracion_sintac ::= VACIO PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 50: // declaracion_sintac ::= REGLA ID DOS_PUNTOS producciones PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 49: // declaracion_sintac ::= INICIO DOS_PUNTOS ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 48: // declaracion_sintac ::= NO_TERMINALES DOS_PUNTOS ids_noterminales PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 47: // declaracion_sintac ::= TERMINALES DOS_PUNTOS ids_terminales PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_sintac",22, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 46: // lista_declaracion_sintac ::= declaracion_sintac 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_declaracion_sintac",21, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 45: // lista_declaracion_sintac ::= lista_declaracion_sintac declaracion_sintac 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_declaracion_sintac",21, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 44: // seccion_sintactico ::= SECCION ANALISIS_SINTACTICO LLAVE_ABRE lista_declaracion_sintac LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion_sintactico",20, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 43: // entrada_transicion ::= OTRO 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("entrada_transicion",46, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 42: // entrada_transicion ::= CADENA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("entrada_transicion",46, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 41: // entrada_transicion ::= ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("entrada_transicion",46, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 40: // transicion ::= PAREN_ABRE ID COMA entrada_transicion PAREN_CIERRA OPE_TRANSICION ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("transicion",45, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-7)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 39: // lista_transiciones ::= transicion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_transiciones",44, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 38: // lista_transiciones ::= lista_transiciones transicion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_transiciones",44, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 37: // estado_final ::= ID OPE_ASIGNACION ID 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("estado_final",18, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 36: // lista_estados_finales ::= lista_estados_finales COMA estado_final 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_estados_finales",17, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 35: // lista_estados_finales ::= estado_final 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_estados_finales",17, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 34: // lista_estados ::= lista_estados COMA ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.peek()).value;
		
  Sintaxis.tabla.registrarIdentificador((String)id,idleft+1,idright+1);
  Sintaxis.tabla.asignarTipoyDireccion((String)id,"ESTADO");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_estados",16, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 33: // lista_estados ::= ID 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.peek()).value;
		
  Sintaxis.tabla.registrarIdentificador((String)id,idleft+1,idright+1);
  Sintaxis.tabla.asignarTipoyDireccion((String)id,"ESTADO");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_estados",16, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 32: // decl_automata ::= TRANSICIONES LLAVE_ABRE lista_transiciones LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_automata",15, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // decl_automata ::= ESTADOS_FINALES DOS_PUNTOS CORCHETE_ABRE lista_estados_finales CORCHETE_CIERRA PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_automata",15, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // decl_automata ::= ESTADO_INICIAL DOS_PUNTOS ID PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_automata",15, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // decl_automata ::= ESTADOS DOS_PUNTOS lista_estados PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_automata",15, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // lista_decl_automata ::= decl_automata 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_automata",14, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // lista_decl_automata ::= lista_decl_automata decl_automata 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_automata",14, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // def_automata ::= EJECUTAR_AUTOMATA LLAVE_ABRE lista_decl_automata LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("def_automata",13, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // decl_token ::= TOKEN ID PUNTO_COMA 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).value;
		
   parser.tabla.registrarIdentificador((String)id, idleft+1, idright+1);
   parser.tabla.asignarTipoyDireccion((String)id, "TOKEN");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_token",11, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // decl_pal_res ::= PALABRAS_RESERVADAS OPE_ASIGNACION CORCHETE_ABRE lista_elementos CORCHETE_CIERRA PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("decl_pal_res",12, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // lista_decl_tokens ::= decl_pal_res 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_tokens",10, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // lista_decl_tokens ::= decl_token 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_tokens",10, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // lista_decl_tokens ::= lista_decl_tokens decl_token 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_decl_tokens",10, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // def_tokens ::= DEFINIR_TOKENS LLAVE_ABRE lista_decl_tokens LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("def_tokens",9, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // lista_elementos ::= lista_elementos COMA CADENA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_elementos",19, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-2)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // lista_elementos ::= CADENA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_elementos",19, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // conjunto_decl ::= CONJUNTO ID OPE_ASIGNACION CORCHETE_ABRE lista_elementos CORCHETE_CIERRA PUNTO_COMA 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-5)).value;
		
   parser.tabla.registrarIdentificador((String)id, idleft+1, idright+1);
   parser.tabla.asignarTipoyDireccion((String)id, "CONJUNTO");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("conjunto_decl",8, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-6)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // lista_conjuntos ::= conjunto_decl 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_conjuntos",7, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // lista_conjuntos ::= lista_conjuntos conjunto_decl 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_conjuntos",7, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // def_alfabeto ::= DEFINIR_ALFABETO LLAVE_ABRE lista_conjuntos LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("def_alfabeto",6, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-3)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // declaracion_lex ::= def_automata 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_lex",5, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // declaracion_lex ::= def_tokens 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_lex",5, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // declaracion_lex ::= def_alfabeto 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("declaracion_lex",5, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // lista_declaracion_lex ::= declaracion_lex 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_declaracion_lex",4, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // lista_declaracion_lex ::= lista_declaracion_lex declaracion_lex 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_declaracion_lex",4, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // seccion_lexico ::= SECCION ANALISIS_LEXICO LLAVE_ABRE lista_declaracion_lex LLAVE_CIERRA 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion_lexico",3, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-4)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // seccion ::= seccion_tabla 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion",2, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // seccion ::= seccion_principal 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion",2, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // seccion ::= seccion_sintactico 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion",2, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // seccion ::= seccion_lexico 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("seccion",2, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_secciones ::= seccion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_secciones",1, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_secciones ::= lista_secciones seccion 
            {
              Object RESULT =null;

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("lista_secciones",1, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // programa ::= COMPILAR ID LLAVE_ABRE lista_secciones LLAVE_CIERRA EJECUTARPROG ID PUNTO_COMA 
            {
              Object RESULT =null;
		int idleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-6)).left;
		int idright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-6)).right;
		Object id = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-6)).value;
		
    parser.tabla.registrarIdentificador((String)id, idleft+1, idright+1);
    parser.tabla.asignarTipoyDireccion((String)id, "PROGRAMA");

              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("programa",0, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-7)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          return CUP$Sintaxis$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= programa EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)).value;
		RESULT = start_val;
              CUP$Sintaxis$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.elementAt(CUP$Sintaxis$top-1)), ((java_cup.runtime.Symbol)CUP$Sintaxis$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$Sintaxis$parser.done_parsing();
          return CUP$Sintaxis$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number found in internal parse table");

        }
    }
}

