
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Dec 14 00:00:49 MST 2025
//----------------------------------------------------

package codigo;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int OPE_ASIGNACION = 41;
  public static final int NUMERO = 57;
  public static final int DIBUJAR = 34;
  public static final int CONJUNTO = 13;
  public static final int TRANSICIONES = 20;
  public static final int OTRO = 21;
  public static final int IMPRIMIR = 29;
  public static final int SI = 7;
  public static final int EJECUTARPROG = 62;
  public static final int LIMPIAR_ERRORES = 38;
  public static final int ESTADOS = 17;
  public static final int REGLA = 60;
  public static final int DOS_PUNTOS = 50;
  public static final int TOKENS = 31;
  public static final int PAREN_CIERRA = 48;
  public static final int TERMINALES = 33;
  public static final int FIN_SI = 9;
  public static final int PRINCIPAL = 6;
  public static final int OPE_TRANSICION = 54;
  public static final int EJECUTAR_AUTOMATA = 16;
  public static final int GENERAR_TS = 26;
  public static final int SINO = 8;
  public static final int CORCHETE_CIERRA = 53;
  public static final int MIENTRAS = 10;
  public static final int COMPILAR = 2;
  public static final int TOKEN = 32;
  public static final int CONSTRUIR_TABLA = 27;
  public static final int ANALISIS_LEXICO = 4;
  public static final int ID = 55;
  public static final int PUNTO_COMA = 51;
  public static final int EOF = 0;
  public static final int CAMPO = 24;
  public static final int PALABRAS_RESERVADAS = 15;
  public static final int error = 1;
  public static final int ESTADOS_FINALES = 19;
  public static final int COMA = 49;
  public static final int CADENA = 56;
  public static final int TABLA = 25;
  public static final int VERIFICAR_ERRORES = 36;
  public static final int LLAVE_ABRE = 45;
  public static final int FIN_MIENTRAS = 11;
  public static final int ARBOL = 30;
  public static final int DEFINIR_ALFABETO = 12;
  public static final int CORCHETE_ABRE = 52;
  public static final int ENTRADA = 28;
  public static final int ANALISIS_SINTACTICO = 5;
  public static final int ESTRUCTURA_TABLA = 23;
  public static final int PAREN_ABRE = 47;
  public static final int OPE_LOGICO = 44;
  public static final int DEFINIR_TOKENS = 14;
  public static final int VACIO = 59;
  public static final int CARGAR_ARCHIVO = 35;
  public static final int VER_ERRORES = 37;
  public static final int ESTADO_INICIAL = 18;
  public static final int LLAVE_CIERRA = 46;
  public static final int TABLA_SIMBOLOS = 22;
  public static final int INICIO = 61;
  public static final int OPE_RELACIONAL = 43;
  public static final int OPE_ARITMETICO = 42;
  public static final int LINEA = 39;
  public static final int SECCION = 3;
  public static final int COLUMNA = 40;
  public static final int NO_TERMINALES = 58;
}

